### ISSUE TITLE
usage examples: automatically execute limit (filter) upon selection

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#620] opened 2019-06-14 15:24 UTC
@abrasax points out that the extra step to click "Get Results" when you have chosen a limit on author or work is unnecessary.  

Selecting an author should execute the author search immediately. This will fix another bug - which is that currently when you select an author, the only works listed are those that are in the unfiltered results, which have been restricted to only 3 results per author (by default). If we execute the author search immediately upon selection, then we can populate the list of texts the user can use based upon those results, which will give the full list of of texts the word appears in for that author

Then selecting a text should immediately execute the search for the text.

This, together with #619 will allow us to eliminate the "Get Results" button entirely.

**Comment by irina060981** [comment] 2019-06-19 23:33
Merged and closed

**Comment by balmas** [comment] 2019-06-20 12:45
ready for testing at texts-test

**Comment by monzug** [comment] 2019-06-21 14:53
I tested #619 first and add a comment about the new design. 
if this is the requirement, at least we should change Limit these results by Author and/or Work  into
Limit these results by Author  as I am not able to select the work at this stage. going back to show limits, then we can have limit by author and/or work.

I am still getting 3 results per author.

**Comment by balmas** [comment] 2019-06-21 15:09
>I am still getting 3 results per author.

Confirmed that is still a problem. it might be contributing to the problems with the design.

**Comment by balmas** [comment] 2019-06-21 15:19
>at least we should change Limit these results by Author and/or Work into
Limit these results by Author as I am not able to select the work at this stage.

I agree we should change this text. It should probably just say "Limit to" and I don't think we actually need the radio button anymore, do we?

**Comment by monzug** [comment] 2019-06-21 15:40
let me think about it.

**Comment by monzug** [comment] 2019-06-23 12:47
click on show limits:
1) remove radio button 
2) limit these results by Author  (remove and/or Work)
3) sort by Author - it's not necessary as it's in alphabetical order, right?
when author is selected, then we can show Limit the results by Author and/or work (not sure about the sorting here as we displays only 3 per authors)

what do you think?

**Comment by irina060981** [comment] 2019-06-24 03:08
>I am still getting 3 results per author.

It is not clear for me quite.
We have 3 results per author, because when we limit results to author/textwork , we simply filter that result that we got without limits from concordance source.
Because we removed (hide) the variant to request more results from the source.

**Comment by monzug** [comment] 2019-06-24 07:23
Irina, you are right.  if I change the limit to 9, then I get 9 results. I thought I got what the problem was but now I am confused... @balmas?
Anyhow, looking at this, I found out something else that is not quite right. When I change the limit to 9 or 10 or 11, the authors list is populated by different authors.
to repro:
go to Cicero and double click on patres. (https://texts-test.alpheios.net/text/urn:cts:latinLit:phi0474.phi019.perseus-lat2/passage/1-5)
default limit is 3, author list is displayed in alphabetical order with aulus gellius first and Vitruvius last.
change the limit to 9. now the authors list is populated by author Annius Florus first and Valerius Maximum last.
change again max results per author to 3. and double click to same word: patres and go to examples. look at the authors list, it's populated by authors not in alphabetical order and can't find Annius Florus.
let me dig more here.

**Comment by irina060981** [comment] 2019-06-24 09:24
Interesting catch, @monzug :)
I  checked it and was able to reproduce this "bug" - it is from concordance algorithm
I will describe.

The option `Word Usage Examples - max results per author` is used to construct url to concordance and that's all.
you could see it in network tab.

Let's go by your steps:
for example first lookup `patres` and open Examples
it executes this url and gets results (authmax=3):
https://latin.packhum.org/rst/concordance/patres?authmax=3&max=10000000

![image](https://user-images.githubusercontent.com/12377640/60007231-3f7e4e80-96b5-11e9-8eaf-1838fe9bee6e.png)

Here it is - it shows 2 texworks (look at the search field in right up corner)

Then let's change the parameter to 9  (authmax=9):
https://latin.packhum.org/rst/concordance/patres?authmax=9&max=10000000

![image](https://user-images.githubusercontent.com/12377640/60007364-80766300-96b5-11e9-817f-3f02d3b7caf0.png)

And again change parameter to 3 (authmax=3) and retrieves data from the same url
https://latin.packhum.org/rst/concordance/patres?authmax=3&max=10000000

And we will have another textwork list without Floral
![image](https://user-images.githubusercontent.com/12377640/60007463-aa2f8a00-96b5-11e9-94b2-008411e1d7f8.png)

So we couldn't change anything here.

**Comment by monzug** [comment] 2019-06-24 10:04
Thanks for looking into it. interesting scenario: not only we don't get the same authors list but it's not in alphabetical order either.

**Comment by irina060981** [comment] 2019-06-24 11:09
>but it's not in alphabetical order either.
@monzug , what do you mean here?

It is sorted by Author+Textwork by default (not cit)
as I could see it is in alphabetical order
![image](https://user-images.githubusercontent.com/12377640/60014402-495b7e00-96c4-11e9-83c6-b868ba3c82e6.png)

**Comment by monzug** [comment] 2019-06-24 11:12
the author list in the dropdown

**Comment by irina060981** [comment] 2019-06-24 11:16
Strange, I couldn't reproduce it.
My steps:
1. lookup 'patres`  - alphabetical
2. change setting to 9 and lookup 'patres`  - again alphabetical
3. change setting to 3 and lookup 'patres`  - again alphabetical (but no Floral)

Could you show me the steps and screenshot not-alphabetical authors?

**Comment by balmas** [comment] 2019-06-24 11:55
(just a note, the author list in the drop down is going to be improved with the next build,  which has the fix for alpheios-project/client-adapters#18) . It won't change anything here but might be easier to use.

**Comment by balmas** [comment] 2019-06-24 11:57
question, are we hitting the max results limit and that's why the service is outputting different authors?

**Comment by irina060981** [comment] 2019-06-24 12:00
no, we change only one parameter authmax
https://latin.packhum.org/rst/concordance/patres?authmax=3&max=10000000
https://latin.packhum.org/rst/concordance/patres?authmax=9&max=10000000
https://latin.packhum.org/rst/concordance/patres?authmax=3&max=10000000

As I could see that it changes the order of result for each request, it seems to me that there is no sorting order. May be it is a reason?

**Comment by monzug** [comment] 2019-06-24 12:26
here is a sample of authors list not in alphabetical order in dropdown
![IMG_3640](https://user-images.githubusercontent.com/41396793/60018609-d0bfd780-9659-11e9-9330-24bdbbc79de2.PNG)

**Comment by balmas** [comment] 2019-06-24 14:02
I understand a little bit more of what's going on here. We have mixed concepts -- limiting current results, and getting more results. I will try to clean this up...

**Comment by balmas** [comment] 2019-06-24 14:02
... meaning clean up the requirements :-)

**Comment by monzug** [comment] 2019-06-24 14:04
please, I am really confused right now. I did also check the Phi site for
some enlightenment!!!!

**Comment by balmas** [comment] 2019-06-24 18:32
Ok, I think there are both bugs and unclear requirements here.  

Here's what I think is the workflow @abrasax was requesting:


![usageexamples](https://user-images.githubusercontent.com/644870/60042912-da166780-968c-11e9-97a5-307d42e0bc62.png)

**Comment by balmas** [comment] 2019-06-24 18:35
what I think we lose here is the ability to request more results for a specific author/work combination, but the UI for that just seems more complicated than it is worth to me.  So let's try to see if we can get this workflow working for now.

@irina060981 I think one problem is the use of a watch for the selectedAuthor and selectedWork -- that was issuing multiple searches because as soon as a search executed, the variables change and then another one executed.  I think we need to use @change handlers on the select elements instead.

**Comment by balmas** [comment] 2019-06-25 12:55
Additional refinements under discussion so let's hold off on implementing until then

**Comment by balmas** [comment] 2019-06-25 20:47
ok, @abrasax and I discussed this today and decided that we need to simplify things further.  We would like to drop the option to Limit current results and rename (again, sorry) the option to request more results for an author/work to "Author Focus" and "Work Focus". The revised workflow, which hopefully makes this clearer is as follows:

![Gliffy-Viewer](https://user-images.githubusercontent.com/644870/60132098-d6f0a980-9768-11e9-85a3-7d337254f1f6.png)

**Comment by balmas** [comment] 2019-06-25 20:51
A few important changes to note:

1) we would like to increase the default authmax setting from 500 to 5000
2) when we offer the Work Focus, we want to offer ALL works for an Author, not just those that were in the prior results (since some might have been left out due to the max results setting)
3) when we request more results for a Work (aka Work Focus) the default sort should be by preceding word

Very sorry for all the changes here, we needed to see it in action with all options in order to be able to refine down the workflow to what made the most sense given the service features available to us.

**Comment by irina060981** [comment] 2019-06-26 11:18
>@irina060981 I think one problem is the use of a watch for the selectedAuthor and selectedWork -- that was issuing multiple searches because as soon as a search executed, the variables change and then another one executed. I think we need to use @change handlers on the select elements instead.

Great, I have missed this !

**Comment by irina060981** [comment] 2019-06-26 11:51
>ok, @abrasax and I discussed this today and decided that we need to simplify things further. We would like to drop the option to Limit current results and rename (again, sorry) the option to request more results for an author/work to "Author Focus" and "Work Focus". The revised workflow, which hopefully makes this clearer is as follows:

Some questions about the workflow:
1. we have a condition - examples Already Retrieved , but for now it is always retrieved (we retrieve examples on tab open) - so by this workflow - I should switch off auto recieving data on tab open or not?

2.When we have this choice
   - Clear Author Focus
   - Focus on Work (with Select List of all OTHER works for Author)
   - Sort by following
    Should it be 3 radio-buttons ?

By the way it is really great to get an explanation via such schema! It is much clearer!

2.

**Comment by balmas** [comment] 2019-06-26 12:19
>we have a condition - examples Already Retrieved , but for now it is always retrieved (we retrieve examples on tab open) - so by this workflow - I should switch off auto recieving data on tab open or not?

What I was trying to show there was the possible condition of the usage examples tab being __reopened__ after the initial open. Does that make sense? I want the auto receiving of tab on open to stay the same as before but we don't need to do it more than per word lookup, correct?

**Comment by balmas** [comment] 2019-06-26 12:20
>2.When we have this choice
Clear Author Focus
Focus on Work (with Select List of all OTHER works for Author)
Sort by following
Should it be 3 radio-buttons ?

I don't think we need radio buttons at all anymore.  There aren't any either/or choices.

**Comment by balmas** [comment] 2019-06-26 12:22
So, for example, I was envisioning that in the above scenario we would see

text:Current Author button or link: Clear
Work select list
Sort as it currently is

**Comment by irina060981** [comment] 2019-06-28 10:57
So I have got the following:
1. Request on opening the tab
![image](https://user-images.githubusercontent.com/12377640/60336580-1545cd00-99e4-11e9-9ed6-2b80d968edde.png)

I have added a progress text, because it spends some time for getting data - and sometimes it is difficult to understand what is going here.

2. Got data without author/textWork limits

**Comment by irina060981** [comment] 2019-07-01 12:31
Merged and closed

**Comment by balmas** [comment] 2019-07-03 12:39
in embed-lib 1.0.0.26/webextension qa-3.0.0.44

**Comment by monzug** [comment] 2019-07-03 15:20
I am confused on the new redesign. I will plan to spend sometimes to digest it. however I want to ask why we want to show all works for an author even if there are no entries for the search word. I saw your comment: when we offer the Work Focus, we want to offer ALL works for an Author, not just those that were in the prior results (since some might have been left out due to the max results setting). ok.  as a user I want to see the works with the search word in it, rather then getting there is no results. it can be misleading, thinking it's an error.

**Comment by balmas** [comment] 2019-07-03 15:54
It's a bit of a compromise, needed because we don't have the ability to change how the server works.

the server does not support pagination and we have to set a maximum number of results to be retrieved.

So we can't really know when we do a search for an author if we are getting all results across all author works or not. We just get the results up until the max is hit.

If we make the max ridiculously high, then we could probably be pretty sure we had everything but then we'd have to deal with paginating that on the client side and the the delay to retrieve could be long

For uncommon words and authors with only a few works, the current max of 5000 is probably high enough. But for common words it might miss some.

The only way to be sure is to search each work. We could do this behind the scenes but it could mean a lot of requests the majority of which would be unnecessary.

**Comment by monzug** [comment] 2019-07-08 15:51
here is the author drop-down pic not in alphabetical order. More to come.
![IMG_3692](https://user-images.githubusercontent.com/41396793/60823968-be27c100-a176-11e9-8750-bf94ccacb201.jpg)

**Comment by balmas** [comment] 2019-07-09 15:34
latest design changes per #632 implemented in webextension qa-3.0.0.45/Safari3.0.0.45)/embed-lib 1.0.0.27 

If sorting problem can still be reproduced, let's make a new issue for it.

**Closed** 2019-07-09 15:34 UTC
Labels: bug, design, discussion, waiting_verification

**Comment by monzug** [comment] 2019-07-11 19:29
enter author drop-down issue as #681
