### ISSUE TITLE
iphone xr: filter by this session (super minor issue)

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#539] opened 2019-05-12 15:00 UTC
tested on mobile iPhone xr  in texts beta (1.0.0.11)
Note that on Samsung or mac, drop-down selection works fine.
login and go to the saved user word list. Click on filter by this session for Latin words (or Greek word). click on done. the field is not populated by the filter. I need to scroll down to the next filter and then back to by this session to get it populated.

**Comment by irina060981** [comment] 2019-05-13 12:59
@balmas , I tried to reproduce it today on desktop (Chrome emulation)  and on my phone - and I haven't seen disappeared filters.
My steps:

select a word
open word list
filter by current session
close panel
select another word
open wordlist
=> wordlist is still filtered and it is still in place

Could you advice me how to reproduce the bug?

**Comment by monzug** [comment] 2019-05-13 13:33
in iPhone xr, to select by  this session, I have to move down to by important then up to by this session and only then the field is populated. see screenshot, if they can be of any help:
![IMG_3448](https://user-images.githubusercontent.com/41396793/57625404-ca6e1400-7561-11e9-8a40-a10e1d9f661a.PNG)
![IMG_3447](https://user-images.githubusercontent.com/41396793/57625405-ca6e1400-7561-11e9-896c-a58d813564c2.PNG)

**Comment by irina060981** [comment] 2019-05-15 11:28
@monzug, as I couldn't reproduce this bug without iphone (I think the problem could be because of its custom way to show select's options), I will try to imagine it and try to guess.
I haven't quitely understand - let's again

first you have empty selection's choice
then you open the selection to choose `by current session`
    - and the selection doesn't have it at the top
    then you scroll to the bottom, select `by important`, click done
    then open the selection again and could choose `by current session`
    am I right?

I could imagine two reasons:
    - `by current selection` is used by default and selection doesn't show it when you try to select it (but I see in screen shot that it is empty)
    - for some reasons `by current session` is out of visible scope of selection (I have read that sometimes there is such bug)

the first reason could be solved by clearing the filter on every time tab becomes visible
the second - we could check by changing the order

@monzug , what do you think?

**Comment by monzug** [comment] 2019-05-15 11:53
I think it's a problem with the iPhone and the drop-down selection. I checked the iPhone 6s and it does the same thing. basically in order to 'activate' the first option in drop-down, I have to scroll to the second one and then back to the fist one, then I can click done and the field is populated (in the example above, by current session)

**Comment by irina060981** [comment] 2019-05-15 12:27
Oh I have an idea - let's check - I will add a placeholder for the selection - may be it helps to show properly the selection.
@monzug , I have uploaded a test page with this changes to this link
http://alpheios-test5.irina-sklyarova.ru/demo/

you could simply open the link from the Iphone, select the word, go to wordlist and try to select `by current session`

Could you make this check? Does it solve the problem?

**Comment by irina060981** [comment] 2019-05-17 08:09
@monzug , did you have time to check the page on your iphone xr?

**Comment by monzug** [comment] 2019-05-17 12:00
here I am

**Comment by monzug** [comment] 2019-05-17 12:01
Irina, I did not see your previous message. sorry about it but I did not get any notification from GitHub...

**Comment by irina060981** [comment] 2019-05-17 12:04
@monzug , don't worry :)
I would be glad to get test results on your iphone - when you will have time for that :)

**Comment by monzug** [comment] 2019-05-17 12:12
I can see that you add Select a filter (not selectable). smart move. t works well. could you also do that for examples?

**Comment by irina060981** [comment] 2019-05-17 12:24
oh, great!
yes, I will add it to filters and sort both on wordlist and wordUsageExamples
Thank you!

**Comment by monzug** [comment] 2019-05-17 12:53
Thank you!!!! sorry again for the missed notification. maybe I should check
my GitHub account settings.

**Comment by irina060981** [comment] 2019-05-17 12:57
Don't worry, sometimes it happens, there are much notifications from github.

**Comment by irina060981** [comment] 2019-05-17 13:14
Ok 
It would be this way
![image](https://user-images.githubusercontent.com/12377640/57930527-8714fc00-78f9-11e9-8bd9-beb43159aa8d.png)

**Comment by irina060981** [comment] 2019-05-17 23:19
merged and closed

**Comment by balmas** [comment] 2019-05-24 17:52
test in texts-beta
embed-lib 1.0.0.16
webext 3.0.0.37

**Comment by monzug** [comment] 2019-05-25 16:19
Thanks for implementing the perfect workaround for this issue.
One super minor thing (if there is an other build befor ethe beta, otherwise it can wait): while Select a filter is never in bold, the other headers (Select an author, Select a textwork, Select sorting type) in Examples are in bold and selectable. Can they be like in wordlist? Thanks

**Comment by irina060981** [comment] 2019-05-27 08:48
merged and closed

**Comment by balmas** [comment] 2019-05-27 15:50
can test in texts-beta embed-lib 1.0.0.17

**Comment by monzug** [comment] 2019-05-27 22:16
Select sorting type is not grayed out in the dropdown on iPhone xr. Can we apply the same fix on this one too? this can wait after the realese.

**Comment by irina060981** [comment] 2019-05-28 11:12
@monzug , you are quite right - I have missed to setup it on sorting panel.
Will fix it

**Comment by irina060981** [comment] 2019-05-28 11:58
merged and closed

**Closed by irina060981** 2019-05-28 11:58 UTC
Labels: bug, waiting_merge

**Comment by balmas** [comment] 2019-05-28 13:28
can be tested in texts-beta embed-lib 1.0.0.18

**Comment by monzug** [comment] 2019-05-28 13:43
YES!!!! thanks
