### ISSUE TITLE
issues with use of preferredLanguage and textLanguage in Lookup from toolbar

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#703] opened 2019-07-26 15:53 UTC
when I have default language greek, and I do enter a latin word in lookup, the change language to latin does not take effect, so lookup fails. I have to select Greek and then Latin again from the drop-down in order to work.
see screenshot

![bello-not-latin](https://user-images.githubusercontent.com/41396793/61964432-d29ff200-af9b-11e9-9bc5-4f66e49eb63f.JPG)

**Comment by irina060981** [comment] 2019-07-31 12:41
While working on this issue, I have faced with the following confusing behaviour:

1. If I select, for example, `እግዚአብሔር` and if I type to lookup field `እግዚአብሔር`
    I will recieve the following
    
![image](https://user-images.githubusercontent.com/12377640/62175482-4453b380-b381-11e9-9cdb-7b54f8cdda7b.png)
    

To avoid it I should guess to open help tab and change language there

2. If I would change language there to Geez (on help tab) - it would be saved only if I would make a lookup, otherwise it returns to previous value. It could lead to the following:

     change Latin to Geez 
     try to lookup using a toolbar lookup - it would change Geez to Latin bck and show no result

3. I type to lookup field a wrong word
![image](https://user-images.githubusercontent.com/12377640/62175812-51bd6d80-b382-11e9-9a79-71cdceb09d39.png)

And it suggests to change the language (and the field is self-saved - if I choose the last time greek - it would show greek), this select is not synchronized with the selection on help tab.
So changing this selection makes no sense and doesn't init any action

_Originally posted by @irina060981 in https://github.com/alpheios-project/components/issues/697#issuecomment-516650407_

**Comment by balmas** [comment] 2019-08-02 16:31
Ok, instigated by the issues reported here, some additional problems listed below, the desire for consistency across the mobile and desktop UI, and prior discussions with @abrasax I have decided to make some changes to the the lookup functionality for the release.

In addition to the problems noted above, in debugging this I found the following:

- the UI between desktop and mobile was inconsistent because without the info tab on mobile, the user could only do a lookup requesting a different language when on the definition tab, which was definitely not intuitive.

- the resource selection on the lookup box on the info and definition tabs no longer worked as I would have expected, given the current UI. I had wanted to keep that option available to the user, so that they could lookup a word in a different dictionary if they didn't like the definition they got, but (1) this is only relevant for languages with multiple dictionaries and (2) as coded it actually only changed the short definition not the full, and really it's most likely what the user would want here would be to look for a full definition in another resource. 

- the decision to remove the language selection from the toolbar lookup resulted in some confusing situations, as noted above in the issues reported by @monzug and @irina060981 . There was just no way to make the error messages make sense when the user didn't get a choice of language in the first place.

I have therefore made the following decisions:

1) to remove the lookup entirely from the panel (info and definition tabs) and only offer it via the toolbar

2) to NOT offer the option to use a different dictionary resources when using the lookup box. The user can still change their preferred dictionaries via options, but allowing per lookup choices for a dictionary will have to wait. It would make sense to do this if/when we implement dictionary browsing, which is requested for at least Arabic.

3) to add the ability for the user to change the language used in the lookup from the toolbar. By default it shows them the language used and a link to change it, which will open the selection box. This is close to what we have in the current 2.x release. 

4) in the error condition where a word is not found, to only show the language switcher in the error message when the lookup was activated by a click on the page, rather than an entry in the lookup box or from the wordlist. In the former situation, it is not obvious what language will be used, because we try to deduce it from the page. So offering the user the choice to change here makes sense. For the lookup box, the user can see or change the language used and it is not clear what the correct behavior would be vis-a-vis the settings if we offer the option to change it on the popup after a failed search.  In the wordlist, if a word is in the list in the wrong language, they should just delete it from their wordlist and look it up using the right language to get it in the right place on the list.


Here's how the the changes impact the UI

On the desktop, default without change language select box shown

![l1](https://user-images.githubusercontent.com/644870/62384528-a3036380-b520-11e9-82cb-9b236b939a6a.png)

On the desktop, after clicking on "Change Language"
![l2](https://user-images.githubusercontent.com/644870/62384578-be6e6e80-b520-11e9-941b-7c062a8bef5f.png)

(rather than using a "Hide" link, I just have it reset when the user closes the lookup box)

On mobile, default without change language select box shown (Note that I have also decided to move the lookup and toolbar up closer to the top of the screen on the alpheios texts interface on mobile.)

![l4](https://user-images.githubusercontent.com/644870/62384635-e067f100-b520-11e9-8147-82866c41ae61.png)

On the mobile, after touching  "Change Language"

![l5](https://user-images.githubusercontent.com/644870/62384649-ebbb1c80-b520-11e9-8256-5595d1b1a779.png)

Message shown when no results found and search was from lookup box:

![l3](https://user-images.githubusercontent.com/644870/62384684-0c837200-b521-11e9-97eb-b7973787f82f.png)

And here is on mobile, when it's not the Alpheios reader interface (where lookup and tools are together)

![AwesomeScreenshot-127-0-0-1-demo-auth html-2019-08-02_12_30](https://user-images.githubusercontent.com/644870/62384836-73a12680-b521-11e9-93f2-5f9c697d5960.png)

![AwesomeScreenshot-127-0-0-1-demo-auth html-2019-08-02_12_30](https://user-images.githubusercontent.com/644870/62384838-769c1700-b521-11e9-8eec-964b1d3b4c36.png)

**Comment by balmas** [comment] 2019-08-02 17:42
qa-3.0.0.51/components 1.2.17/embed-lib 1.0.0.34

**Comment by monzug** [comment] 2019-08-04 17:33
Maybe I was used to the previous functionality that I could not see all the issues listed above. Sorry about it. However I found few things that don't work right now.
1) I always keep the lookup open so it's not obvious that in order to change language I have to close the lookup (after the initial change of language), as said:
"(rather than using a "Hide" link, I just have it reset when the user closes the lookup box)"
2) after the initial successful change of language in lookup, any subsequent change of language does not take effect, unless I execute a search.
3) when I change language in lookup, it does also change language in double-click. if I want to change language from the morphology pop-up, let's say from Greek to Latin which is the default entry in the language field then I click on the x button, the change language doesn't work, so the bug reported here is still valid.

to make it easier to follow, see scenario below:
start fresh, double click on any word of latin text, the morphology pop-up shows up. open the lookup from the toolbar, it says that language is latin. change language to greek and enter an invalid word. language is greek in both lookup and in the error pop-up. double click on the latin text, lexical query produced no results. language is greek and it offers the option to change to latin (which does not work). I go back to lookup and I change the language to Latin in drop-down (I don't close the lookup or execute a lookup): double click is still in Greek, the language in Option is Latin. If I close the lookup and open again, the change language has taken effect in the lookup (it says the language) but not in the double click, so they are not in sync. the only way to change language in the lookup is to execute a search.

I haven't looked at the mobile version yet, or word list or logged in versus not logged

![latin-language](https://user-images.githubusercontent.com/41396793/62426904-fc05ff80-b6b8-11e9-8d8d-c85cd7aad3e5.JPG)

**Comment by irina060981** [comment] 2019-08-05 11:45
@monzug , I have other results of checking this changes:

1. I tried to lookup different words through toolbar - after each lookup (by clicking the button and by Enter) it always returnd to this state - so there was no problem to rechoose the language
![image](https://user-images.githubusercontent.com/12377640/62462048-bd139f00-b7c9-11e9-8b8e-47c2a0b0318c.png)

2. >when I change language in lookup, it does also change language in double-click. if I want to change language from the morphology pop-up, let's say from Greek to Latin which is the default entry in the language field then I click on the x button, the change language doesn't work, so the bug reported here is still valid.

I was not able to reproduce that - lookup language didn't mix with language for double click

As for my tests - everything works well according to @balmas description - I tested using embed-lib

**Comment by balmas** [comment] 2019-08-05 11:48
>I always keep the lookup open so it's not obvious that in order to change language I have to close the lookup (after the initial change of language), as said:
"(rather than using a "Hide" link, I just have it reset when the user closes the lookup box)"

It should not be the case that you have to close the lookup to effect the language change. I just meant that in order to remove the change language selection box from the lookup popup you need to close it.

**Comment by monzug** [comment] 2019-08-05 13:06
so, issue 1) is a gladly non-issue. how about 2) and 3)? I tested in Alpheios Reading Tools 3.0.0.51
Alpheios Components 1.2.17 in both Chrome and FF on desktop.
 I am going to test on mobile now

**Comment by monzug** [comment] 2019-08-05 13:18
the mobile works smoothly as described from @balmas. could it be that I do not have the most update version on desktop?

**Comment by balmas** [comment] 2019-08-05 13:21
I was able to reproduce at least one problem with changing the language from the lookup tool in the browser extension. Am investigating that now.

**Comment by monzug** [comment] 2019-08-05 13:22
Thanks!!! I hold testing on this for now.

**Comment by balmas** [comment] 2019-08-05 14:14
>when I change language in lookup, it does also change language in double-click. if I want to change language from the morphology pop-up, let's say from Greek to Latin which is the default entry in the language field then I click on the x button, the change language doesn't work, so the bug reported here is still valid.

found the bug that was causing this.  Actually a long -standing bug that was made more obvious by this change. Instead of using the default page language when we can't identify the language of a word, we were using the last language used for a successful lookup (regardless of source).

**Comment by balmas** [comment] 2019-08-05 14:18
>after the initial successful change of language in lookup, any subsequent change of language does not take effect, unless I execute a search.

this one I can't reproduce

**Comment by balmas** [comment] 2019-08-05 14:27
@monzug can you retest now in qa-3.0.0.52/components 1.2.18 ?
(same code will be up in text environment shortly too)

**Comment by monzug** [comment] 2019-08-05 14:30
yes, better test on  a fresh environment

**Closed** 2019-08-05 14:41 UTC
Labels: bug, waiting_verification

**Comment by monzug** [comment] 2019-08-06 16:51
still testing.

**Comment by monzug** [comment] 2019-08-07 15:42
it works as described, so in case of data error from lookup and double-click, we have now the following pop-ups:

double-click
![pop-up-invalid-word](https://user-images.githubusercontent.com/41396793/62636843-4d57fe00-b908-11e9-9e0c-fb0270b5fe9a.JPG)

look-up
![lookup-invalid-word](https://user-images.githubusercontent.com/41396793/62636845-4d57fe00-b908-11e9-9784-27a95fe24c19.JPG)

**Comment by balmas** [comment] 2019-08-07 17:02
yes, although I am making the error messages more consistent in #731
