### ISSUE TITLE
Changing language doesn't work when the language is defined in the page

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#746] opened 2019-08-09 14:09 UTC
this is related to issue #703  - the scope and title of the issue were changed. today I was able to reproduce the original issue:
when I have default language greek, and I do enter a latin word in lookup, the change language to latin does not take effect, so lookup fails. I have to select Greek and then Latin again from the drop-down in order to work.

to repro in build 3.0.0.53
have default language set to greek in options, then go to latin text. double click on any latin word, the lookup will fail with the option to change language from Greek to Latin. click on the close button, next lookup will fail again. only when switching language from latin to greek and back to latin from drop-down , the lookup will not fail.
this scenario is only reproducible when change language is from Greek to Latin (or the other way)

**Comment by balmas** [comment] 2019-08-09 17:55
hmm. I cannot reproduce this.  I did these steps:

on a latin library text

default language in settings set to greek
click on a word
in the language fail notice, Greek is preselected, change it to Latin
close the popup
lookup another word
it correctly uses latin

**Comment by monzug** [comment] 2019-08-10 13:55
not easy to repro, specially after fixing #703.  you have to have a situation in which on latin text you have a pop-up in which it says language not greek. change to latin.

**Comment by monzug** [comment] 2019-08-10 13:59
![sync-lang](https://user-images.githubusercontent.com/41396793/62822756-8f29b400-bb55-11e9-872f-76e7963811e2.JPG)

**Comment by monzug** [comment] 2019-08-10 14:01
to repro:
from above latin library text, I change page language to greek in options, then I enter a greek word in lookup. then I double click a latin word from text. that's when I start getting the above message and the switch to latin works only when I select greek and then latin from drop-down

**Comment by monzug** [comment] 2019-08-12 15:06
I was able to reproduce a similar scenario in safari build 3.0.0.53 in which Venus worked from lookup but not from double-click
see screenshot
![Screen Shot 2019-08-12 at 4 36 56 PM](https://user-images.githubusercontent.com/41396793/62875547-81298e00-bd23-11e9-9b58-adad64f419a7.png)

**Comment by balmas** [comment] 2019-08-15 22:25
@irina060981 can you try investigating this? Thank you!

**Comment by irina060981** [comment] 2019-08-20 09:47
I couldn't understand it quitely

As I could see steps are the following:
      - options page language = greek (then when you double click any word it tries to search all in greek, if other is not defined in page layout directly)
      - lookup language doesn't update from the page language setting (that's why it has Latin)
      - double click on any word - it shows the message - no in Greek (got from settings) - change to Latin?
      - you change to Latin (it updates page setting to Latin) and then double-click again
      - it searches in Latin with success

These steps I could guess from the description and screenshots.
I see the same steps and even I spent time to describe it in video tutorial because it could be rather confusing.

But no I am confused :)
@balmas, @monzug , What is not working correctly here?

**Comment by monzug** [comment] 2019-08-20 12:18
Irina,
try the following. go to
https://www.loebclassics.com/view/augustus-res_gestae/1924/pb_LCL152.345.xml?rskey=U4vflA&result=1
and log in. text is in both languages, latin and greek. activate alpheios
(page language is Latin), double click on a greek word. it will say that
the word is not found in the Latin resources, wrong language? change to:
select greek from drop-down.
double click again to an other greek word, you will still get the same
message over and over.

**Comment by balmas** [comment] 2019-08-20 12:51
ah... I think I see what's failing here. 

The Loeb site has the greek text with an ancester html element which identifies the language as latin.

So the change in the select box IS taking effect, but it is being overridden by the page settings.

```
<section class="div1 language" lang="la"><header><hgroup><h1><span class="hi">Res</span> <span class="hi">Gestae</span> Divi Augusti</h1></hgroup></header>
<section class="div2">
<h2><span class="ac"><span class="hi">Res</span> <span class="hi">Gestae</span> Divi Augusti</span></h2>

<p>Rérum<a href="#note_LCL152_344_1" class="footnoteLink" id="target_note_LCL152_344_1"><sup>1</sup></a> gestárum díví Augusti, quibus orbem terra-(<span class="italic">rum</span>) ímperio populi Rom. subiécit, § et inpensarum, quas in rem publicam populumque Ro(<span class="italic">ma</span>)num fecit, incísarum in duabus aheneís pílís, quae su(<span class="italic">n</span>)t Romae positae, exemplar sub(<span class="italic">i</span>)ectum.</p>
</section>

<section class="div2">
<p><span class="marginNote left partNote">I</span>1 Annós undéviginti natus exercitum priváto consilio et privatá impensá | comparávi, (§) per quem rem publicam (<span class="italic">do</span>)minatione factionis oppressam | in</p>

<p>Μεθηρμηνευμέναι ὑπεγράφησαν πράξεις τε καὶ
δωρεαὶ Σεβαστοῦ θεοῦ, ἃς ἀπέλιπεν ἐπὶ Ῥώμης
ἐνκεχαραγμένας χαλκαῖς στήλαις δυσί.</p>
</section>

```

**Comment by balmas** [comment] 2019-08-20 12:56
We don't actually offer the option to override the page markup.  I think this one might have to wait.

**Comment by monzug** [comment] 2019-08-20 13:06
ok. but I have experienced this situation in almost all sites not just
loeb. it's just not easy to repro

**Comment by balmas** [comment] 2019-08-20 13:29
hmm. ok. that was what I was going to ask, if you were able to reproduce elsewhere. If that's the case, then my analysis is not correct.

**Comment by monzug** [comment] 2019-08-20 13:35
but it's correct to say that we don't override the page language when offering to change language

**Comment by balmas** [comment] 2019-08-20 14:55
I cannot reproduce it in a scenario where the language is not defined in the page markup.

**Comment by irina060981** [comment] 2019-08-22 11:27
i have checked the code - and @balmas , you are right.
It works with the following steps:

 - selected text is sent via event/domEvent
 - it defines the language from the source (each time selection is done); and if it is not defined, it gets the default language from options

   on the current Loeb link - `lang=la` is defined for the whole left text - for the latin part and for the greek part.
    So Latin language would be applied to any selection in both pieces of text

**Comment by irina060981** [comment] 2019-08-22 11:29
@monzug and @balmas ,
May be then we could close this issue and reopen when someone will find the link with the scenario - page language is not defined, but default language is overwritten?

**Comment by balmas** [comment] 2019-08-22 12:00
well, I would like to leave this open for the scenario we have identified. We won't probably fix it for this release but it should be possible to override page language, so we want to keep that for an incremental future release. I will update the title. @monzug if you can reproduce in another scenario, let's open a separate issue for that.

**Comment by monzug** [comment] 2019-08-22 12:35
sounds good to me.

**Comment by monzug** [comment] 2019-09-11 13:18
I was able to repro the above scenario in the safari (Alpheios reading tools 3.0.0.65)
I changed the page language to greek and then I was not longer able to have the language set to latin. I had to select Greek and then latin again from drop-down.
see screenshot
![Screen Shot 2019-09-11 at 2 44 15 PM](https://user-images.githubusercontent.com/41396793/64700521-56a82d80-d4a7-11e9-869d-ca48747ef877.png)

**Comment by monzug** [comment] 2019-09-14 16:15
to repro:  go to https://scaife.perseus.org/reader/urn:cts:greekLit:tlg0096.tlg002.First1K-grc1:1-4b/
page language is latin by default. note that the text is in Greek. activate Alpheios, then double click on ὑπὸ. You'll get the message that language is Latin, change language to Greek. close the button and double click to an other word such as ἐπώλει  or  δὲ  with same error. now from the message, change the drop-down language from Greek to latin than Greek again. double click on any greek word. it will work fine now.

**Comment by irina060981** [comment] 2019-09-16 09:28
I tried to repro too with the following steps, that @monzug gave.
And I have correct results right after I have changed the language in popup at the first double-click.
So I am not reproducing the bug.

But I have not done the second lookup right away. Because first I checked the options - was the option -page language updated to Greek.

Monica, did you try to check the language first and then get the second word?

**Comment by monzug** [comment] 2019-09-16 10:33
Nope. I did upload a video on dropbox with the above scenario.

**Comment by monzug** [comment] 2019-09-16 10:48
I was just able to reproduce the issue by following the steps described above. so first login then logout. check that page language is latin.  double click on nay greek words, you'll get the message that language is Latin. change language to Greek. close the message. double click on any greek words, you'll get the message over and over again, till you change the language from Greek to Latin then Greek again in drop-down.

**Comment by balmas** [comment] 2019-09-17 14:36
:-( still cannot reproduce.

**Comment by monzug** [comment] 2019-09-18 14:39
my environment? did you login/logout and then follow the steps? I was able
to reproduce it today too

**Comment by balmas** [comment] 2019-09-18 14:40
Yes I followed your steps exactly.

**Comment by monzug** [comment] 2019-09-18 14:42
interesting. did you see the video on dropbox?

**Comment by balmas** [comment] 2019-09-23 12:00
the dropbox video is here
https://www.dropbox.com/s/ueyyoesxldswcrk/Video%2014.09.19%2C%2018%2006%2040.mov?dl=0

I still cannot reproduce this in my environment, but after viewing the video, I see the difference is that when I get the popup with the notification to change language, the preselected value is Latin, as it should be.  But in Monica's case it's Greek. That's why she has to go through the extra step of selecting a different language and then back to Greek.

So, It seems that this is happening because the preselected language in the change language select box is either not selected at all or it's erroneously set to Greek instead of Latin.

**Comment by monzug** [comment] 2019-09-23 12:25
or the other way (latin instead of Greek).  I think it's not selected
that's why I have to scroll down and select from drop-down

**Comment by monzug** [comment] 2019-09-23 12:44
an other one just now, as soon as I logged in 
![maximum](https://user-images.githubusercontent.com/41396793/65426514-5af51480-ddde-11e9-9df9-daf068f42491.JPG)

**Comment by balmas** [comment] 2019-09-23 12:51
hmm. I wonder if this could be caused by a timing issue where the settings are one thing at the time of lookup and another at the time of the error.

In any event, I think we could probably prevent it by making sure that the language that is shown as selected is the same as the language that was used for the lookup. That would require the user to actively change it and avoid the problem I believe,

@irina060981 what do you think?

**Closed** 2019-10-01 11:59 UTC
Labels: bug, waiting_merge

**Comment by monzug** [comment] 2019-10-01 12:01
can't wait to test this one!!!

**Comment by balmas** [comment] 2019-10-01 12:29
qa 3.0.1.74/components 1.2.50

(crossing my fingers...)

**Comment by monzug** [comment] 2019-10-01 14:23
I haven't been able to replicate this so far. Thanks Bridget!!!!

**Comment by monzug** [comment] 2019-10-02 13:15
still investigating this but in https://www.loebclassics.com/abstract/augustus-res_gestae/1924/pb_LCL152.345.xml?rskey=B19U2S&result=1&mainRsKey=fRpqMi
in which we have a mix of greek and latin text, no matter if page language is Greek or Latin, when I double click on any greek word, the change language pops-up and keeps asking to change to latin. if I select greek from drop-down, it does not set greek as language but it's still latin.

![IMG_4021](https://user-images.githubusercontent.com/41396793/66047086-702d1a00-e527-11e9-9d63-9e0df4bbbe35.jpg)

**Comment by monzug** [comment] 2019-10-02 13:18
still finding other reproducible scenarios

**Comment by balmas** [comment] 2019-10-02 13:37
Ah, I got a little confused with this issue.  The issue in the title of the bug is not fixed.  I fixed the scenario when the language shown in the select box was different for some reason than the language used for lookup. But not the ability to override the underlying page language. That requires a bigger fix.

**Comment by monzug** [comment] 2019-10-02 13:40
the one reported in the bug it has been fixed or at least I was not able to
repro. not sure if this is a side effect of the fix, though. I am still
trying to find other scenarios

**Comment by monzug** [comment] 2019-10-02 13:47
so, I found an other text with mix of latin and greek words and change language works like a charm. text is at https://www.thelatinlibrary.com/gellius/gellius12.shtml

not sure what's the problem in https://www.loebclassics.com/abstract/augustus-res_gestae/1924/pb_LCL152.345.xml?rskey=B19U2S&result=1&mainRsKey=fRpqMi  but change language does not work at all. @balmas?

**Comment by balmas** [comment] 2019-10-02 18:28
the problem with loeb is that it explicitly identifies the language of the text as 'la' and that takes precedence over the user preference. That's why this is really two separate issues.

Here's the source of the Loeb page

```
<section class="div1 language" lang="la">
...
<p>Μεθηρμηνευμέναι ὑπεγράφησαν πράξεις τε καὶ
δωρεαὶ Σεβαστοῦ θεοῦ, ἃς ἀπέλιπεν ἐπὶ Ῥώμης
ἐνκεχαραγμένας χαλκαῖς στήλαις δυσί.</p>
</section>
```

fixing this is more complicated than I can put in the incremental. The work around is to copy and paste the text from the page into the lookup and specify the language there.

**Comment by monzug** [comment] 2019-10-03 06:32
finally I got it!!!! sorry for the confusion. so, the issue in Loeb is a different one. will enter a new issue for this so we keep record, no need to fix it but at least it's there!!! I did enter issue #830 for our record. Thanks.
