### ISSUE TITLE
Don't add words without results to the user wordlist

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#598] opened 2019-06-06 14:52 UTC
tested in Firefox 67 build 3.0.0.37
I signed up as new user in Firefox and then select tacitus and liber xiv from latin library, then I double click on a word from the above text. I noticed that the word Tacitus and XIV were added to user word list. when clicking on those words from the user word list, I get the message that lexical data could not be populated because page language is not defined. 
two issues here:
1) authors and book title should not be added to user word list - they don't produce a morphological pop-up
2) the second issue is most likely related to the first one
see screenshots below:

![lexical-data-not-populated](https://user-images.githubusercontent.com/41396793/59042398-61b84580-8848-11e9-86c3-d12dceb08fcb.JPG)

![tacitus-xiv](https://user-images.githubusercontent.com/41396793/59042402-6250dc00-8848-11e9-9ef8-3c861ba18740.JPG)

**Comment by balmas** [comment] 2019-06-07 18:18
hmm. this is a difficult one. We can't always know why we don't get a result and I am not sure we really want to exclude words from the user's word list in that case. Need to think about this a bit.  @abrasax do you have any thoughts? If we can't provide a parse for a word (which might be because it's not a valid word and might be because it's missing in the parser), should it still be added to the user's wordlist?

**Comment by balmas** [comment] 2019-07-11 17:02
after discussion today, @monzug and I have decided that for this release we want exclude words which don't produce lookup results from the wordlist.  It is causing inconsistent behavior when clicking on words in the list and would require some refactoring to make this work well.

**Comment by irina060981** [comment] 2019-07-18 12:52
of course, i will remove it upon requirements - but such words could produce word usage examples anyway - I have saw such variants.
But I completely agree in the current workflow it is confuxing

**Comment by balmas** [comment] 2019-07-22 14:08
I think we need to change the requirements for this issue here, after considering:

1.  the complexity of the code changes necessary for this
2. the need to take into account scenarios such as for Persian, where we might get definitions and no morph data
3. the long term need to include all words the user looks up regardless of whether or not we can parse them

Let's instead continue to add all words the user looks up to the wordlist, but modify how we present them to the user, based upon whether or not the item has any lemmas.

If the worditem's lemmaList property is empty then the target word 
1. should not be clickable in the wordlist.
2. display the message "<unknown>" in place of the lemma in the wordlist display

**Comment by irina060981** [comment] 2019-07-22 23:38
@balmas , I don't think that it is enough check, because we create homonym for any targetWord, even without morph data. 
In this case lemmas list has the only lemma that is equal to the target word 
![image](https://user-images.githubusercontent.com/12377640/61672049-7c2d7c00-ad2d-11e9-9d2b-40572754bc40.png)

It could have definitions.
I think we should add some specific flag to homonym to indicate that it has no morph on creation stage.
What do you think?

**Comment by balmas** [comment] 2019-07-23 11:55
ah, you're right about that.  the problem is no morph doesn't necessarily mean it doesn't have definitions. 
Ultimately, I think I am probably trying to fix the wrong problem here. If issues #502 and #501 were addressed that would probably be sufficient, but I had deemed those out of scope.  Thinking.

**Comment by balmas** [comment] 2019-07-23 15:05
additional notes from debugging with @monzug sometimes we get the PLACEHOLDER_NO_LANGUAGE_DATA message staying in the popup when we click on a word with no morphology from the wordlist (e.g. she can reproduce when double-clicking a title on the Latin Library TOC) . I think this means that the app.morphDataReady state object is never being set. Maybe an error is  short circuiting the code.

**Comment by balmas** [comment] 2019-07-23 15:05
(@irina060981 I'm going to take this back for now until I know better what I want us to do here...)

**Comment by balmas** [comment] 2019-07-23 15:10
also noting that @monzug was able to get a list of words under the "undeflined" language code. This should not be possible...

**Comment by balmas** [comment] 2019-07-24 18:55
@monzug try as I might, I cannot reproduce the error about page language is not defined. I have not been able to get a double-click on a title on the Latin Library toc to add the text to my wordlist.

Were you able to create a clean account with that error reproduced? If so, can you give me the details so I can see what is happening?

**Comment by monzug** [comment] 2019-07-24 19:11
it took me longer than yesterday to be able to repro but I got it again. use the id/psw: latin@test.it  Test@123


see screenshot

![epistulae](https://user-images.githubusercontent.com/41396793/61821472-51beea00-ae25-11e9-92d0-0755047a6d48.JPG)

**Comment by balmas** [comment] 2019-07-24 19:18
excellent! That enabled me to find the bug :-)

**Comment by balmas** [comment] 2019-07-24 19:20
there are couple of issues here

The code that is failing is this (in uiController.onWordItemSelected):

```
    if (homonym.lexemes.length > 0 && homonym.lexemes.filter(l => l.isPopulated()).length === homonym.lexemes.length) {

```

It's producing a javascript error on the test of `homonym.lexemes.length` because `homonym.lexemes` isn't defined.

So we should make that test be sure we have lexemes before we test their length.

But we should also figure out in what circumstances a homonym can be saved to the wordlist with no lexemes property.

**Comment by monzug** [comment] 2019-07-24 19:20
thanks for investigating it!

**Comment by balmas** [comment] 2019-07-24 19:21
thanks for insisting on it :-D

**Comment by balmas** [comment] 2019-07-29 20:12
passing this one back to @irina060981 .

Please fix this test in in uiController.onWordItemSelected) to check to be sure homonyms.lexemes is defined before testing the length, and also take a look to see if you can figure out how it might be possible to save a homonym with an undefined lexemes object. Thanks!

```    if (homonym.lexemes.length > 0 && homonym.lexemes.filter(l => l.isPopulated()).length === homonym.lexemes.length) {```

**Comment by irina060981** [comment] 2019-08-05 13:28
I was not able to reproduce the problem.
Added the check for emptu homonym and homonym.lexemes

Merged and closed

**Closed by irina060981** 2019-08-05 13:28 UTC
Labels: bug, question, waiting_merge

**Comment by balmas** [comment] 2019-08-05 14:41
qa-3.0.0.52/components 1.2.18

should not see the `language is not defined` message anymore in this scenario.

**Comment by monzug** [comment] 2019-08-08 14:55
I got lexical query produced no results. Thanks
