### ISSUE TITLE
Filters are not applied when downloading wordlist file

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#728] opened 2019-08-05 15:34 UTC
from issue #422 :
the download file is a list of all the saved words, ignoring the limit applied. 
About the filters -- I think different users would expect different things and am not sure what is right to do here. For now, I think I'm okay with it ignoring the filters

**Comment by irina060981** [comment] 2019-12-05 09:50
I have added filtering box
if it is checked, then it download the list with applied filters, otherwise - the whole list
By default - it is uncheked

![image](https://user-images.githubusercontent.com/12377640/70222381-bc9a0d80-1795-11ea-857a-40f89812625a.png)

**Comment by irina060981** [comment] 2019-12-05 22:43
merged and closed

**Comment by balmas** [comment] 2019-12-10 14:47
components 1.5.0 (qa-3.0.4.83/embed-lib 3.1.5.46)

**Comment by monzug** [comment] 2019-12-12 15:44
for some reason I cannot check filtering for greek limits. tested in both chrome and FF.
Note that it does work for Latin. any idea?

**Comment by balmas** [comment] 2019-12-12 15:46
sounds like a bug -- giving back to @irina060981

**Comment by irina060981** [comment] 2019-12-13 09:39
I couldn't reproduce it for greek.
I downloaded with filters for both latin and greek.

@monzug could you list all your steps -
   which filter doesn't work?
   or it doesn't work for any filter?
   or  you even doesn't see the checkbox?

**Comment by monzug** [comment] 2019-12-13 13:29
@irina060981 I can't check the check box for greek. see screenshot
![latin-filter-by-important](https://user-images.githubusercontent.com/41396793/70803696-aafeca00-1d82-11ea-9f6b-986db586b849.JPG)
![limit-by-important](https://user-images.githubusercontent.com/41396793/70803697-aafeca00-1d82-11ea-9575-260d53217ef5.JPG)

**Comment by irina060981** [comment] 2019-12-16 08:18
@monzug , thank you for detailed screenshots.
I have found my mistake in the code!

**Comment by monzug** [comment] 2019-12-16 10:19
Cool. Thanks

**Comment by irina060981** [comment] 2019-12-16 12:52
merged and closed

**Closed by irina060981** 2019-12-16 12:52 UTC
Labels: enhancement

**Comment by balmas** [comment] 2019-12-19 13:40
qa-3.0.4.94/components 1.5.1

**Comment by monzug** [comment] 2019-12-27 15:36
tested in chrome and FF build qa-3.0.4.94
