### ISSUE TITLE
Wordlist does not display word info if user is logged out

### ISSUE THREAD

**Issue by kirlat** [alpheios-project/components#409] opened 2019-04-10 12:21 UTC
In the current version of both webextension and embedded library when users clicks on the word from a word list and the user is not logged in, nothing happens. Expected behavior: word info shall be displayed.

Console shows the following warning:

**ui-controller.js:1297 UserDataManager is not defined, data couldn't be loaded from the storage**

| onWordItemSelected | @ | ui-controller.js:1297 |
| -- | -- | -- |
| (anonymous) | @ | ps-event.js:65 |
| pub | @ | ps-event.js:65 |
| selectWordItem | @ | wordlist-controller.js:240 |
| selectWordItem | @ | word-item-panel.vue:82 |
| click | @ | word-item-panel.vue?0d7e:96 |
| invokeWithErrorHandling | @ | vue.js:1863 |
| invoker | @ | vue.js:2188 |
| original._wrapper | @ | vue.js:7541 |

**Comment by balmas** [comment] 2019-04-10 13:01
assigning to @irina060981 to take a look at

**Comment by irina060981** [comment] 2019-04-11 11:04
The problem here is in the fact, that if the user is not logged in, we have no userDataManager - so we don't have any methods for getting data.
```
  async onWordItemSelected (wordItem) {
    if (this.userDataManager) {
      let wordItemFull = await this.userDataManager.query({ dataType: 'WordItem', params: { wordItem } }, { type: 'full' })
      let homonym = wordItemFull[0].homonym
      this.newLexicalRequest(homonym.targetWord, homonym.languageID)

      this.onHomonymReady(homonym)
      this.updateDefinitions(homonym)
      this.updateTranslations(homonym)
    } else {
      console.warn('UserDataManager is not defined, data couldn\'t be loaded from the storage')
    }
  }
```
I have found this problem after the ability to fill wordlist without creating UserDataManager was added and I placed this warning.

So I will look how could I create another to retrive data without userDataManager

**Comment by irina060981** [comment] 2019-04-11 11:42
It turned out to be really a small fix - because we are storing the whole homonym with all definitions, inflections inside memory.
So here it is a PR for that - https://github.com/alpheios-project/components/pull/413

By the way, for now we don't have any limits here - no limits for the number of the word, no limits for storing types of data (definitions and inflections, lemma translations) - so it could be a source memory/CPU leaks.

Once in testing in Firefox I have more than 2GB of RAM spent for the wmbed-lib page, I tried later to reproduce - but it was max 1Gb. So I couldn't show the tests and correct steps, I am sorry.

**Comment by irina060981** [comment] 2019-04-11 12:03
Merged and closed

**Comment by balmas** [comment] 2019-04-14 23:22
can be tested in 3.0.0.26 (https://github.com/alpheios-project/webextension/tree/qa-3.0.0.26/dist and Dropbox)

**Comment by monzug** [comment] 2019-04-15 16:29
I do still see the problem. if I am not logged in and I double click on few words, the saved words in word list look like link (on mouse over) but don't produce any word info.
when I am logged in, I can click on the words in wordlist and they show the word info.

**Comment by irina060981** [comment] 2019-04-15 23:05
@monzug , it is really strange - 
but in my last branch I couldn't see any problem with it .
Also I have checked master branch - it is working too.

I couldn't find out the exact problem in your build - because I couldn't see there what components package was used (it is minified inside build package).
But may be there is no useful changes there?

@balmas , what do you think?

**Comment by monzug** [comment] 2019-04-16 08:26
Irina, the build 3.0.0.26 failed to install so I took the files from
master. I just noticed that 3.0.0.26branch is one commit ahead of master.
could it be that your fix is not in my current build. I'll take back the
issue and wait for next build. Thanks for checking.

**Comment by irina060981** [comment] 2019-04-16 08:38
ok, let's wait fot the next build for testing - thank you for the information!

**Comment by balmas** [comment] 2019-04-16 13:30
hmm, the build can't be the difference because the only change in the qa branch is the inclusion of the auth test files.  I will look into the problem with the build though and make sure we have a clean one with the fix.

**Comment by balmas** [comment] 2019-04-16 23:14
let's try again in the build at https://github.com/alpheios-project/webextension/tree/qa-3.0.0.27/dist (sorry no Safari build yet)

**Comment by monzug** [comment] 2019-04-17 17:06
this works now in Chrome, build 3.0.0.27

**Closed** 2019-04-25 11:37 UTC
Labels: bug

**Comment by balmas** [comment] 2019-04-30 13:51
in webextension qa-3.0.0.30 and texts-test (embed-lib 1.0.0.6)
(https://github.com/alpheios-project/webextension/tree/qa-3.0.0.30/dist and Dropbox)

**Comment by monzug** [comment] 2019-05-05 20:13
verified in chrome and firefox 3.0.0.31
