### ISSUE TITLE
need to revisit usage examples and wordlist filtering ui in compact (mobile) panel

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#477] opened 2019-04-25 18:12 UTC
the filter options take up a lot of room at the top of the usage examples tab on a mobile device. 

we need a design that works better on mobile for that. Not sure what it is.

**Comment by balmas** [comment] 2019-05-06 15:28
additional feedback from @monzug 

4) mobile only:
- the Clear filter by icon is below the drop-down (I guess for space issues), Pls confirm.
- because of the above, the tooltip is partially visible (I can only see "er by")
- Show context icon is visible only for the latest word added, then it disappears. if I click to Show context when available, it shows only the word with the 'back to word list' option with no link or passages info.

**Comment by irina060981** [comment] 2019-05-09 11:47
For compact view:
I could suggest only this variant - reduce spaces and add show/hide button

**Comment by irina060981** [comment] 2019-05-09 11:50
![Screenshot_20190509-213124](https://user-images.githubusercontent.com/12377640/57451372-64a13400-72a4-11e9-8a40-8f500d9dd6d2.png)
![Uploading Screenshot_20190509-213138.png…]()

**Comment by irina060981** [comment] 2019-05-09 11:52
![Screenshot_20190509-213138](https://user-images.githubusercontent.com/12377640/57451457-acc05680-72a4-11e9-9961-b8821d329510.png)

**Comment by irina060981** [comment] 2019-05-09 11:57
For wordlist - it looks like this now
![image](https://user-images.githubusercontent.com/12377640/57451652-3c660500-72a5-11e9-9cfb-82dff15a97fd.png)

I think it is already compact - it is only 2 rows.
@monzug and @balmas , do you have any ideas  what could be decreased here?
Or may be again - show/hide link for filters block?

**Comment by irina060981** [comment] 2019-05-09 12:02
> the Clear filter by icon is below the drop-down (I guess for space issues), Pls confirm.
> because of the above, the tooltip is partially visible (I can only see "er by")
> Show context icon is visible only for the latest word added, then it disappears. if I click to Show context when available, it shows only the word with the 'back to word list' option with no link or passages info.

I couldn't reproduce it on my mobile
For me it looks like this

**Comment by irina060981** [comment] 2019-05-09 12:03
![Screenshot_20190509-220011](https://user-images.githubusercontent.com/12377640/57452065-3de3fd00-72a6-11e9-9a38-10c330057458.png)

**Comment by irina060981** [comment] 2019-05-09 12:35
Changes for word usage examples - merged

**Comment by monzug** [comment] 2019-05-09 13:15
Irina, I have Samsung 5s. will try on iPhone 6s and the new iPhone xr that just arrived today. tooltips are visible when finger is over the related icons.

**Comment by monzug** [comment] 2019-05-09 13:24
![IMG_3442](https://user-images.githubusercontent.com/41396793/57456816-4bfd3380-723c-11e9-986c-b3d55df771dc.JPG)

**Comment by irina060981** [comment] 2019-05-10 11:45
Hope I fixed it here - waiting for the check from @monzug after it will be merged :)

**Comment by irina060981** [comment] 2019-05-10 12:31
merged and closed

**Closed by irina060981** 2019-05-10 12:31 UTC
Labels: design, mobile, waiting_merge
