### ISSUE TITLE
Logged out but word list icon still hangs there

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#428] opened 2019-04-12 13:11 UTC
tested in Firefox 3.0.0.25
I clicked on logout and the message that I have been logged out is displayed in the User info panel. However the word list icon is still there and so it's the content of the word list.
question: shall we clear the content of the word list when we log out?
Possible scenario if the computer is shared by multiple users.

**Comment by irina060981** [comment] 2019-04-16 10:50
I have checked this bug with my last branch (https://github.com/alpheios-project/components/pull/438)
I couldn't reproduce it both in Chrome and in Firefox
I think it shoould be retested in the future build

**Comment by monzug** [comment] 2019-04-16 12:42
still reproducible in build 3.0.0.26. let's wait for next build.

**Comment by balmas** [comment] 2019-04-16 23:09
@monzug you can test this with the build at https://github.com/alpheios-project/webextension/tree/qa-3.0.0.27/dist (sorry no Safari build yet)

**Comment by monzug** [comment] 2019-04-17 17:00
tested again in Chrome build 3.0.0.27 - see screenshot
![log-out-wordlist](https://user-images.githubusercontent.com/41396793/56306487-9a715380-6110-11e9-8acc-11cdfe3ec8f9.JPG)
I do log out but wordlist is still populated by the previous user's list. only on reload the wordlist is clear and the icon is inactive.

**Comment by irina060981** [comment] 2019-04-17 23:26
I think that https://github.com/alpheios-project/webextension/tree/qa-3.0.0.27/dist
is not the last build, because it shows me errors that I fixed on Monday

![image](https://user-images.githubusercontent.com/12377640/56327060-fb099a80-61bb-11e9-9080-42448a82dbb7.png)

**Comment by balmas** [comment] 2019-04-18 11:53
hmm you're right. that's weird. it has commit 7d0215562eae57e83c74f673cc5eb3f2b1cd312e of components, even though I was sure I had updated everything. Sorry for this @monzug I will get the built right one of these days.

**Comment by monzug** [comment] 2019-04-18 12:21
hahaha, spring is in the air... should I wait for a new one?

**Comment by balmas** [comment] 2019-04-18 12:22
yes please, coming soon

**Comment by monzug** [comment] 2019-04-18 12:22
Thanks

**Comment by balmas** [comment] 2019-04-18 12:31
please try https://github.com/alpheios-project/webextension/tree/qa-3.0.0.28/dist

**Comment by monzug** [comment] 2019-04-18 13:24
this is fixed in build 3.0.0.28. Thanks!

**Closed** 2019-04-18 16:06 UTC
Labels: verified
