### ISSUE TITLE
Firtst double click, the noun inflection is not loaded

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#657] opened 2019-07-02 14:17 UTC
double click on commodis from https://texts-test.alpheios.net/text/urn:cts:latinLit:phi0474.phi004.perseus-lat2/passage/1-5

then go to inflection, it does not show the table for the noun as it says not existing yet. switch to the adjective table and then back to noun, it works.

if I lookup for commodis, the table is generated. any subsequent double click (including on commodis) works fine. reload the page, again I don't get the noun inflection table for commodis. tested on firefox and chrome

an other one is rapinis

![rapinis](https://user-images.githubusercontent.com/41396793/60519881-6985d100-9cb2-11e9-8ee0-2e488bc5ac6f.JPG)
![commodis](https://user-images.githubusercontent.com/41396793/60519882-6985d100-9cb2-11e9-8a26-66da117e35e7.JPG)

**Comment by monzug** [comment] 2019-07-02 14:36
also periculum on iPhone XR (Safari)

**Comment by kirlat** [comment] 2019-07-04 14:03
I've tested it on texts-test.alpheios.net and somehow I cannot reproduce the issue. With a freshly loaded page that was specified in the issue I do see the noun declension inflection table when I double click the words listed in the issue: commodis and rapinis.

![image](https://user-images.githubusercontent.com/18631055/60671716-bf11d780-9e84-11e9-9cbd-a2f2e804d26d.png)

It might be not related but probably worth noting that @balmas was installing a fresh version of `code-optimization` branch to the server. However, this branch has the same code for rendering inflection tables as `master`.

I've also tested a `master` version of components with the Nemo UI locally and it still works fine for me.

@balmas, can you please check if it is working for you when you will have time? I'm wondering if this is environment related somehow.

**Comment by balmas** [comment] 2019-07-09 11:45
hmm. I can't reproduce either. It's possible it was related to the code-optimization branch -- we should retest when that is merged.

**Comment by monzug** [comment] 2019-07-10 15:27
still able to repro on latest build 3.0.0.45 in Chrome 
this is in Scaife, double click on a noun, table is not generated, double click on a verb, the inflection table is generated.

see screenshot
![remis](https://user-images.githubusercontent.com/41396793/60981237-f4df1200-a303-11e9-8b6a-cc7e51e653d0.JPG)

if it's something in my environment, what can it be???? so, I usually remove build, clear browsing data, install new build.
Also, I do override the dist folder of qa- 3.0.0.25 (with the authentication) with the dist folder of latest build. 
Is there anyhing wrong in the above steps?

**Comment by balmas** [comment] 2019-07-10 16:25
That's very strange. are there any errors in the developer console? (In Chrome, open Tools, Developer Tools and click on the Console tab)

**Comment by monzug** [comment] 2019-07-10 16:44
how about firefox browser console?
![error console](https://user-images.githubusercontent.com/41396793/60987730-3970aa80-a310-11e9-8df1-96655f60855f.JPG)

**Comment by balmas** [comment] 2019-07-10 17:12
hmm. It looks like you're not using the latest env-embed.js file from the qa-3.0.0.45 tag.  Can you double check? It should be this one: https://github.com/alpheios-project/webextension/blob/qa-3.0.0.45/dist/env-webext.js

**Comment by monzug** [comment] 2019-07-10 17:34
that's what I have in my dist directory for qa 3.0.0.45
const auth0Env = {
  AUTH0_DOMAIN: 'alpheios.auth0.com',
  AUTH0_CLIENT_ID: 'iT75HkBHThA4QdFwFoZRofLC41vVyvAt',
  ENDPOINTS: {
    'wordlist' : 'https://userapis.alpheios.net/v1/words',
    'settings' : 'https://settings.alpheios.net/v1/settings'
  },
  AUDIENCE: 'alpheios.net:apis',
  LOGOUT_URL: 'https://alpheios.net/pages/logout'

**Comment by balmas** [comment] 2019-07-10 17:40
odd. this error would indicate that it isn't seeing that :
`auth.endpoints.settings` is undefined

although I am not sure it would have any impact on the inflection tables. That error be something that would happen upon login (and would cause problems for you in testing #519) so it's probably not the issue here anyway.

A little stumped...

**Comment by monzug** [comment] 2019-07-10 17:54
it has to be my environment though.

**Comment by balmas** [comment] 2019-07-10 18:03
Is it only in Firefox now? Or does it happen in Chrome too?

**Comment by balmas** [comment] 2019-07-10 18:08
But if you do the same steps in chrome as if what happens?

**Comment by monzug** [comment] 2019-07-10 18:08
I found one noun in Chrome:

![hostis-console-chrome](https://user-images.githubusercontent.com/41396793/60993315-35e32080-a31c-11e9-92a3-d118c5adebbd.JPG)

**Comment by balmas** [comment] 2019-07-10 18:09
I guess try removing the build completely and reinstalling.

**Comment by monzug** [comment] 2019-07-10 18:10
for hostis as in the above screenshot, if I select verb from drop-down and then noun, the inflection is generated

**Comment by balmas** [comment] 2019-07-10 18:11
I will do a clean install from the tag dist on my side too to try again to reproduce

**Comment by monzug** [comment] 2019-07-10 18:17
I removed building chrome, clean data, reinstall. it worked for few words, then I enter hostis from lookup and got again the noun table not implemented
![again-hostis](https://user-images.githubusercontent.com/41396793/60993951-7abb8700-a31d-11e9-992e-eacff6f09b92.JPG)

**Comment by balmas** [comment] 2019-07-10 18:23
ok. I have now reproduced too. Not on the first lookup but the 2nd.

**Comment by balmas** [comment] 2019-07-10 18:23
Giving this one back to @kirlat 

Something about the state of the inflection tables isn't quite right.

**Comment by balmas** [comment] 2019-07-10 18:29
yes, I agree it isn't specific to the 2nd lookup. But somehow the state isn't getting properly set or retained.

**Comment by kirlat** [comment] 2019-07-11 17:01
I was able to reproduce it (hooray!), will work on a fix

**Comment by kirlat** [comment] 2019-07-19 18:18
A fix has been merged into master as of now

**Comment by monzug** [comment] 2019-07-19 19:57
Great! can't wait to test it. Thanks

**Closed** 2019-07-22 15:30 UTC
Labels: bug, performance, waiting_build, waiting_verification

**Comment by balmas** [comment] 2019-07-22 17:34
in qa-3.0.0.47/components 1.2.6

**Comment by monzug** [comment] 2019-07-24 15:33
Unable to repro in FF and Chrome. Thanks!!!!!!!!
