### ISSUE TITLE
set z-index of popup

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#122] opened 2018-06-19 21:06 UTC
we already calculate the highest z-index for the page in UIController.getZindexMax and use that to set the zIndex of the panel. We also need to set the z-index of the popup. 

Found while debugging #120 - google drive display has a high z-index and the popup disappears under it.

**Comment by irina060981** [comment] 2018-07-02 03:30
I have changed z-index recalc
https://github.com/alpheios-project/components/pull/134

**Comment by irina060981** [comment] 2018-07-02 03:31
I spent some time for investigation and figured out that the problem is in getting textSelection.
The google doc has such structure - every line is wraped in a special span
for example
![image](https://user-images.githubusercontent.com/12377640/42144036-362cb092-7dfc-11e8-9867-9ab9b4077cf0.png)

**Comment by irina060981** [comment] 2018-07-02 12:19
Merged and closed

**Closed** 2018-07-02 13:08 UTC
Labels: bug
