### ISSUE TITLE
User word list: previous inflection table generated from pop-up

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#802] opened 2019-09-16 15:49 UTC
from user word list, click on any saved word such as omnes (as in the screenshot below), the related inflection table is the one generated for the previous lookup word from user word list (e.g. contigit).

![user-word-list](https://user-images.githubusercontent.com/41396793/64972390-35648a00-d877-11e9-833a-00e5a8ddb4ce.JPG)

**Comment by balmas** [comment] 2019-09-17 13:33
can you take a look at this one @kirlat ?

**Comment by kirlat** [comment] 2019-09-17 13:38
Definitely!

**Comment by kirlat** [comment] 2019-09-17 18:13
A fix has been merged into `alpheios-release-3.0`

**Comment by balmas** [comment] 2019-09-17 18:43
in v3.0.0.67/components 1.2.44

**Closed by balmas** 2019-09-17 18:43 UTC
Labels: bug

**Comment by balmas** [comment] 2019-09-17 19:00
@monzug note that I believe this bug could only be reproduced in the following scenario:

While **logged out**:

lookup word a
lookup word b
click on word a in wordlist - note that inflection table is still that of word b

it was not reproducible for me and @kirlat when logged in to a User account. 

The problem seemed to be caused by the fact that in the case where you are not logged in, if you click on a word in the wordlist, the data for the popup comes from memory very quickly (vs a little delay that happens when it gets loaded from the user data storage) and the change to the state variable that tells the inflections tab to update itself wasn't getting picked up because it happened too fast. So the change is to make sure the state variable gets updated before the browser redraws the inflections tab.

**Comment by monzug** [comment] 2019-09-18 13:13
tested in in v3.0.0.67/components 1.2.44 - both logged in/out
