### ISSUE TITLE
Improve display when no popup data but there are full definitions.

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#833] opened 2019-10-08 13:19 UTC
double click on Apulia in http://www.thelatinlibrary.com/varro.rr2.html. initially the pop-up will say Lexical query produced no results but then it sticks with an empty pop-up. see screenshot
I looked at whitaker and it does not return anything.
I think we should still display Lexical query produced no results
![apulia](https://user-images.githubusercontent.com/41396793/66398928-a269cc00-e9ac-11e9-9508-fc1d06e1aead.JPG)

**Comment by balmas** [comment] 2019-10-10 12:34
agree we should improve this. See also #835

**Comment by irina060981** [comment] 2019-12-05 10:32
I have checked the problem with Apulia.
It has no results from morph adapter.

But it has the result from full definitions:
![image](https://user-images.githubusercontent.com/12377640/70227189-e5be9c00-179d-11ea-96c0-e3fe11b98520.png)

But our check `hasMorphData` includes check for full definitions
that's why - we have flag `hasMorphData` but have no MorphData

@monzug and @balmas , May be we should remove full definitions from the check?
So it would have - Lexical query produced no results
and active definitions icon and word usage icons

**Comment by irina060981** [comment] 2019-12-05 10:46
I think it is about the same
https://github.com/alpheios-project/components/issues/501

**Comment by balmas** [comment] 2019-12-05 19:00
I'm not really sure what is best here. I think it could be equally confusing to the user to show the Lexical Query Has No Results error with the defintions and word usage icons active.   

@monzug do you have an opinion on this?

**Comment by balmas** [comment] 2020-02-11 17:21
dupe of alpheios-core#122

**Closed by balmas** 2020-02-11 17:21 UTC
Labels: bug
