### ISSUE TITLE
scrolling oddities in word usage examples on mobile

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#573] opened 2019-05-22 15:05 UTC
Some oddities in word usage examples on mobile (Samsung 5 mini and iphone xr):
1) lookup for fero and go to the word usage examples and click on Get results.
Have show source links on. click on any link, it's very difficult to have the source underline and selectable as link, specially when moving from landscape to portrait view. Frequently, it does open a morphological popup related to the word on which the finger was on.
2) on iPhone xr, I can't scroll the results in landscape view (I thought I have reported this issue already but could not find any reference)
3) I did also experience a scrolling problem as per 2) in normal view on iPhone xr. I did lookup and got results in the examples for the same word several times (between 8 to 10 times).  on the last one, I could not scroll the results any longer in normal view. could not move up the popup. I could only close it. Now I can't get the get results to work (log in or out, looking up a word or by clicking on a word from text). will try later on
see screenshot 
![IMG_3483](https://user-images.githubusercontent.com/41396793/58185265-b8d2ed80-7c80-11e9-81f1-d05c549c05f7.PNG)

**Comment by balmas** [comment] 2019-05-23 11:11
I'm going to split this into two issues, one for the scrolling, and one for the lookups.

**Comment by balmas** [comment] 2019-05-23 11:15
item 1 is now in #575. This issue is for the scrolling difficulties.

**Comment by monzug** [comment] 2019-05-23 11:43
I have still some testing to do for 3)

**Comment by monzug** [comment] 2019-05-23 13:56
as per 3), scrolling in portrait view on iPhone xr.  if I don't expand the Get results view, I have the scrolling problem. The pop-up does not scroll below Select sorting type entry field. If I expand to full screen (via the arrow) then I can scroll through the results.
Definitely when I stress the functionality with lots of get results, there is some instability like the scenario described above in this issue. 
also, I can't read the full sentence from the Results, unless I move left to right from the filters top screen. I can't move left to right any sentence within the Results.

**Comment by monzug** [comment] 2019-05-24 13:18
here are two screenshots from examples for 'dilatio' on Samsung 5mini (scrolling) and iPhone xr (not scrolling)
![IMG_3487](https://user-images.githubusercontent.com/41396793/58330413-d29d3d80-7e04-11e9-9eac-dd2eb2de014e.jpg)
![IMG_3488](https://user-images.githubusercontent.com/41396793/58330421-d761f180-7e04-11e9-9e1e-3b3d52236a95.PNG)

**Comment by balmas** [comment] 2019-05-24 17:38
@kirlat can you investigate this when you get a chance? It would be nice to fix for the beta if we do another build before then but if not then soon after. thanks.

**Comment by kirlat** [comment] 2019-05-24 17:50
Sure, will do. Hope I will be able to reproduce it!

**Comment by monzug** [comment] 2019-05-25 14:48
as I was testing issue #397 , I can confirm that I still can't scroll in landscape view

**Comment by balmas** [comment] 2019-05-28 13:29
can be tested in texts-beta embed-lib 1.0.0.18

**Comment by monzug** [comment] 2019-05-28 15:18
Definitely some improvements, thanks!!!  however, if show source links is on, I can't scroll down much (between 7 to 10 source links in expanded portrait view) then it bounces back up. same in landscape view where it's also difficult to click on show/hide source links without experiencing the transparency problem (lookup for links or source). Also, on Samsung I see the same problem with the show/hide source links. scrolling is fine on Samsung.

**Comment by kirlat** [comment] 2019-05-29 14:26
I was able to reproduce the issue with the show/hide links button and I submitted a fix for that. I've also reduced an active zone of the source link itself which might help to prevent it from being activated accidentally when scrolling.

However, I was not able to reproduce bouncing back when scrolling on the devices I have (iPhone 6s, Redmi 1S). Will do more testing trying to catch that.

**Comment by balmas** [comment] 2019-06-07 19:12
@monzug and I tested the show/hide links button and that does seem to be fixed now.  But the scrolling problems remain. See also #583 which I think might be the same issue for the wordlist.

**Comment by kirlat** [comment] 2019-06-10 06:18
@balmas, @monzug, does the scrolling issue affects only iPhone XR (i.e. it may be present on some other phones but I mean is the iPhone XR the only phone at our disposal that has this issue)? I've tried to reproduce it on iPhone 6s and I do not see this thin appearing.

**Comment by balmas** [comment] 2019-06-10 11:23
Happens on the iPhone X too, in both the usage examples and the wordlist

**Comment by balmas** [comment] 2019-06-11 17:53
@irina060981 can you reproduce this on the iPhone 7?

**Comment by irina060981** [comment] 2019-06-11 23:58
I have made two different tests - 

1. I have uploaded a simple page with embed-lib 
    http://alpheios-test7.irina-sklyarova.ru/demo/

And I couldn't reproduce here any problems with scrolling and clicking on the source link

2. I have tested text-beta.alpheios.net
I opened a latin text and try to lookup.

And here I see the fillowing problem - clicking on the source link (in any mode) scrolls the panel to the header instead of opening the source link.
So when you try to scroll, and in our design source link is on the every second line - it is easy to click on it when scroll down and it moves panel to the header.

I think that the problem is in the texts-beta layout - I will try to investigate more.

**Comment by balmas** [comment] 2019-06-12 14:11
Ah that's interesting. @monzug can you try to reproduce the scrolling problems at https://balmas.github.io/alpheios-embed-demo/ ?

**Comment by monzug** [comment] 2019-06-12 14:36
I used the balmas page on gitgub. I can still reproduce the scrolling issue described above on iPhone xr. will try on iPhone 6s

**Comment by monzug** [comment] 2019-06-12 15:11
was able to reproduce the scrolling problem on iPhone 6s too.

**Comment by irina060981** [comment] 2019-06-13 10:03
For some unknown reasons - my previous link started to work in a very strange way - it shows empty panel and as I could see chrome console - there is no even any lexiqal requests.
Clearing cach, renaming domain didn't help (I would postpone this strange behaviour for some repeat).

I have created a new link - I pushe there sample.html with dist folder from embed-lib repo and now it works without any jumping - 
http://alpheios-test-embed.irina-sklyarova.ru/

Here  it is a video

**Comment by irina060981** [comment] 2019-06-13 10:18
But both http://text-beta.alpheios.net and https://balmas.github.io/alpheios-embed-demo/
has jumping behaviour

**Comment by irina060981** [comment] 2019-06-13 11:18
I am using on my page master branch of embed-lib with master branches of all repos inside.
@balmas , do you use the last version of embed-lib and components repo on your page?
Could you compare ?

**Comment by balmas** [comment] 2019-06-13 12:09
oh, this is a good point. I have updated my site (https://balmas.github.io/alpheios-embed-demo/) to use a build 1.0.0.22 of embed-lib which is the latest code from master for everything. 

@monzug does this fix it?

**Comment by monzug** [comment] 2019-06-13 12:44
let me check

**Comment by monzug** [comment] 2019-06-13 12:54
landscape view works fine!!!!! portrait view not quite, still bouncing back after several source links. However  if I was able to get to the bottom of the examples page  by scrolling horizontally first (away from the source links) and from there I was able to scroll all the way down without any problem.

**Comment by balmas** [comment] 2019-06-13 17:00
interesting. So that points to the source link html as being the place to focus for the cause.

**Comment by balmas** [comment] 2019-06-13 17:01
maybe the same as with #583, the tool tips @irina060981 ?

**Comment by irina060981** [comment] 2019-06-14 10:38
> maybe the same as with #583, the tool tips @irina060981 ?

I am not sure - because there is no tooltip around a link on word usage examples tab.
I couldn't reproduce it on my source (as I showed in video) but I see that with changes from the PR - it behaves a little other way.

So I hope it could help. Waiting for your tests :)

**Comment by irina060981** [comment] 2019-06-14 12:02
Merged and closed

**Comment by irina060981** [comment] 2019-06-14 12:03
Waiting for your tests and verification!

**Comment by balmas** [comment] 2019-06-18 16:20
ready for testing at texts-test embed-lib 1.0.0.23
webextension 3.0.0.40

**Comment by monzug** [comment] 2019-06-20 14:16
Unfortunately this hasn't been fixed. tested on iPhone xr both in landscape and portrait view. in landscape if I scroll from the right side of the screen, away from the source link, the scrolling works fine, as described in one of my comments above.

**Comment by balmas** [comment] 2019-06-20 15:27
ok, back to @irina060981 to see if she has other ideas about the scrolling

**Comment by balmas** [comment] 2019-07-23 17:54
I did some debugging of this today on Monica's Iphone XR and it seems that the problem is the`<a>` tags for the source links.  Changing those to `<div>` tags resolved the scrolling problem.

So I think the solution is to remove the `<a>` tags, replace them with `<div>` tags with a click handler which opens the source link in a new tag.

**Comment by kirlat** [comment] 2019-07-23 18:09
> I did some debugging of this today on Monica's Iphone XR and it seems that the problem is the`<a>` tags for the source links. Changing those to `<div>` tags resolved the scrolling problem.

Wow! Who would have guessed that? That's a very useful information. I think we should probably start a list of device/OS quirks somewhere. Weird thing like this could slip our mind later because of time passed and also because of a probably natural tendency to hope for the best even though we are not receiving it that often 🙂 🙁.

**Comment by balmas** [comment] 2019-07-23 18:21
> I think we should probably start a list of device/OS quirks somewhere. Weird thing like this could slip our mind later because of time passed and also because of a probably natural tendency to hope for the best even though we are not receiving it that often  .

Good idea.  Will add an iOS label to this issue for now. Post release we should probably take the time to go back and pull together such a list.

**Comment by irina060981** [comment] 2019-07-23 21:54
@balmas , would you finish with this issue? or should I do the changes?

**Comment by balmas** [comment] 2019-07-24 11:45
it would be great if you could do them, @irina060981 . Thank you!

**Comment by irina060981** [comment] 2019-07-24 11:46
ok :)

**Comment by irina060981** [comment] 2019-07-29 07:28
merged and closed

**Closed by irina060981** 2019-07-29 07:28 UTC
Labels: bug, ios, mobile, waiting_merge

**Comment by balmas** [comment] 2019-07-29 22:30
qa-3.0.0.49/components 1.2.12

**Comment by monzug** [comment] 2019-07-31 14:59
scrollable!!!!!! yeahhhh
