### ISSUE TITLE
lookup entry field not visible (mobile only)

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#514] opened 2019-05-08 14:22 UTC
tested on Samsung 5s
the lookup pop-up opens at the top of the page so I can't see the entry field to enter a word for lookup. see screenshot
![IMG_3435](https://user-images.githubusercontent.com/41396793/57382256-974f0d80-717a-11e9-8f36-1d0485a4e728.JPG)

to repro: double click on any word, the morphology pop-up will open, then close it and go back to the overlay and expand it. when entering the new word on the lookup, the pop-up moves up but under the title bar not on the top of it, so the entry field is hidden.

**Comment by kirlat** [comment] 2019-05-09 12:51
Calculating visible area is complicated. It is device dependent, there are complex rules that have to be applied on complex (or naive) layouts and it still may fail in one way or the other. I think we should use the simplest solution we can to solve this.

I did a few tests and, on my opinion, the best way is to switch an action panel into the focus mode with only the input and the button visible, and place it at the bottom of the screen (i.e. right on top of the virtual keyboard):
![image](https://user-images.githubusercontent.com/18631055/57454513-18d99500-727a-11e9-82b8-ae1131ed34ef.png)
This way we will most likely guarantee that it will be within the area visible to the user. 

What do you think about an option like this?

**Comment by monzug** [comment] 2019-05-09 13:02
Kirlat, not sure if this can help but my experience is that lookup pop-up is always visible (it opens on top of the nav bar) except in the scenario above. will try to reproduce on iPhone

**Comment by kirlat** [comment] 2019-05-09 13:19
Here is how I see the problem from the screenshot. The action panel (the one that has a lookup in it) is located at a certain distance from the bottom of the viewport. When a virtual keyboard appears, it shifts the vieport's bottom approximately half way up. This makes the panel move into the upper half of the screen. 

On the screenshot it goes beyond the toolbar, so rising its z-index could help bring it upfront. My concern is, however, that on certain combination of screen size (on smaller ones, probably) and zoom factor (zoom in, most likely) there will not be enough space to fit the action panel into the upper part of the screen. As a result, the panel can become cut-off. 

So I'm thinking that for this special occasion, when half of the screen is occupied with a keyboard, we, to guarantee that the most important thing (the input field) is visible, can reduce its vertical size. This will allow it to fit in easier into the multitude of layout and device combinations.

**Comment by monzug** [comment] 2019-05-09 13:30
Thanks. I have Samsung 5s which has a small screen.

**Comment by balmas** [comment] 2019-05-09 13:35
just a note, which may or may not be relevant. #341 asks for the toolbar icon to be moved to the header of the page. Will opening the action panel at the bottom of the screen still make sense then?

**Comment by monzug** [comment] 2019-05-09 13:50
interesting, it's not reproducible on iPhone 6s (safari). I noticed that on Samsung the morphology pop-up normally opens on the top of the nav bar, in Safari (iPhone 6s) the pop-up opens just above the keyboard.

**Comment by kirlat** [comment] 2019-05-09 13:55
> #341 asks for the toolbar icon to be moved to the header of the page. Will opening the action panel at the bottom of the screen still make sense then?

This is a very hard case to solve. The problem is: Chrome has an auto-zoom feature. When someone selects the input field, Chrome zooms in thus making everything (including the action panel) bigger. And on my device, when lookup is started and the input is blured, the page does not zoom out. This ruins the layout, and the user experience.

This is a "feature" of Chrome people are asking to disable for 6 years and it is still there: https://bugs.chromium.org/p/chromium/issues/detail?id=181560

When zoomed in, the best way to guarantee that something is visible, I think, is to attach it to the bottom of the viewport because we don't know how tall the element will be and how much space is left there. We can do some intricate calculations but I'm not sure how reliable it will be. I suspect there will be a device that will break the most intricate logic with ease 🙂.

So if the button will be on top, it would make no sense to place the panel on the bottom. But then placing it at the bottom is the most "safe", on my opinion, way to do it. Will think more about it.

Also, we're not talking about the panel in general, but about the special case when user starts to type in the lookup word. Considering the current circumstances, I think this probably should be a special form of a panel. On blur, the panel should return to its normal look.

What do you think?

**Comment by balmas** [comment] 2019-05-09 13:58
> Also, we're not talking about the panel in general, but about the special case when user starts to type in the lookup word. Considering the current circumstances, I think this probably should be a special form of a panel. On blur, the panel should return to its normal look.

Yes, this makes sense to me.

**Comment by kirlat** [comment] 2019-05-09 14:01
> interesting, it's not reproducible on iPhone 6s (safari). I noticed that on Samsung the morphology pop-up normally opens on the top of the nav bar, in Safari (iPhone 6s) the pop-up opens just above the keyboard.

The screenshot I've provided is Chrome on Redmi 1S (720x1280). 

The tricky part is, although the position of an action panel is set as "fixed" (i.e. it should stay at a certain position within the viewport), in my tests it is possible to move it around, unfortunately (maybe because the viewport itself is scrollable, probably when zoomed). Scroll the page, and the panel will stay in place, scroll a little more, and the panel may start to shift (but it's all very tricky). So it may also depend on an initial position of a panel (and a device resolution, and a zoom factor, and probably on a combination of stars in the sky 🙂). So I guess we need some truly reliable solution here (if possible).

**Comment by kirlat** [comment] 2019-05-09 14:06
Also,, when part of the panel is out of sight, I believe it is possible to scroll it down. But that's not the best user experience 🙁.

**Comment by monzug** [comment] 2019-05-13 16:14
@kirlat, sorry I missed your question. I am going to try later.

**Comment by monzug** [comment] 2019-05-13 16:32
not able to repro on 1.0.0.12 (Samsung 5s) - the lookup popup opens on top on nav bar. interesting, side effect of some other changes? will keep an eye on it but so far so good.

**Comment by kirlat** [comment] 2019-05-13 16:52
@monzug, I've updated the visibility rules for the action panel so that it will be placed higher than any other elements of the host page.

**Comment by monzug** [comment] 2019-05-13 17:09
Bravo! problem gone. Thanks for fixing it

**Comment by monzug** [comment] 2019-05-14 06:44
actually, I had an issue with the lookup entry field not visible in landscape mode on Samsung 5s (it's the mini version) - see screenshot
![IMG_3451 (1)](https://user-images.githubusercontent.com/41396793/57676256-1b2d4d80-75f2-11e9-9c52-44ef49f2062a.jpg)

**Comment by kirlat** [comment] 2019-05-14 15:59
There viewport is so narrow on the screenshot above between the browser's toolbar and the virtual keyboard so there is no way to display the action bar in its current format. The only way to do it is to reduce the action panel, when in focus, to have just an input as shown below:
![image](https://user-images.githubusercontent.com/18631055/57454513-18d99500-727a-11e9-82b8-ae1131ed34ef.png)
What do you think about that? Are there any other solutions we can use? I'd consider this rather an edge case because there is almost no usable screen space, but we should do our best to support it too, if possible. Samsung 5s has 1920x1080 px resolution, so it gives 1080 px height in landscape, and that's pretty typical for many phones around.

**Comment by monzug** [comment] 2019-05-14 16:04
is there a way to force the user to go in normal view only for that specific action? and then back to landscape view?

**Comment by kirlat** [comment] 2019-05-14 16:41
> is there a way to force the user to go in normal view only for that specific action? and then back to landscape view?

Yes, there is an API for that, but we have yet to see how well it will work on different devices. I can try to implement it and then we can test and see how convenient it will be to use.

**Comment by balmas** [comment] 2019-06-10 12:49
I think I'm going to mark this won't fix for now, pending further user reports.

**Closed by balmas** 2019-06-10 12:49 UTC
Labels: bug, mobile, not_reproducible, waiting_feedback
