### ISSUE TITLE
double-click on example propogates to page below

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#526] opened 2019-05-09 19:59 UTC
on desktop, lookup works in the examples as per requirement. However when double click on a word, the lookup is generated on the word from the text behind the World usage examples panel.
could not activate this functionality on mobile (samsung 5s)

_Originally posted by @monzug in https://github.com/alpheios-project/components/issues/307#issuecomment-490946232_

**Comment by balmas** [comment] 2019-05-09 20:00
maybe it's as simple as adding stopPropogation to the event handler? giving to @irina060981 to investigate.

**Comment by irina060981** [comment] 2019-05-10 11:37
I wasn't able to get lookup from word usage examples on mobile, because compact panel has 
`data-ignore=all`
After I removed - it starts to work - but I wasn't able to reproduce the lookup from background text ... 
I would post this small fix and hope, @monzug , will be able to check in the same environment.

I have uploaded to my server - http://alpheios-test5.irina-sklyarova.ru/demo/
and test on my phone - it is working.

**Comment by irina060981** [comment] 2019-05-10 12:32
Will again check according to @balmas notice
>this looks okay, although I don't think it will fix #526 which I reproduced in the desktop on a latin library page. It might depend upon the positioning of the panel above the page -- i.e. if what you click on in the examples tab isn't positioned directly over a word below. Or, it might depend upon which one finishes first .. i.e. both the examples lookup and the lookup of the word below happened, the word below finished 2nd so it replaced the examples lookup

**Comment by irina060981** [comment] 2019-05-11 04:30
Oh, I was able to reproduce here (in embed-lib I couldn't)
http://www.thelatinlibrary.com/phaedr3.html

Will investigate on this page

**Comment by irina060981** [comment] 2019-05-13 10:12
I have found how it works.
Only webextension has this problem, because we add two listeners:
  - to body
  - to wordUsage tab
So when we click on the tab - it propagates to body and then calculate the place inside body for selection.
I saw variants when it selects the word not at the same place as it was clicked.

That's why we don't have this problem with embed-lib (demo), we attach listeners to divs not to body, and the event couldn't propogate to div - it stops on the body.

I have added `event.stopPropogation()` and it fixed the problem.

**Comment by irina060981** [comment] 2019-05-13 11:44
merged and closed

**Closed by irina060981** 2019-05-13 11:44 UTC
Labels: bug

**Comment by balmas** [comment] 2019-05-16 12:09
in qa-3.0.0.35/1.0.0.13

**Comment by monzug** [comment] 2019-05-17 13:42
verified. Thanks for fixing it.
