### ISSUE TITLE
Mobile: click on Show contexts, it takes up to top of user word list or show filters

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#583] opened 2019-05-12 14:33 UTC
on mobile in texts beta environment (1.0.0.11).

login as user test@test.it, the word list  is a long one and has a mixed of invalid words, latin and greek words. click on Show contexts for a valid latin word (e.g.  minus) from bottom Latin list. it will go at the top of the word list or show the drop-down for the filter.

**Comment by balmas** [comment] 2019-05-24 17:37
maybe for beta -- it depends upon whether we do another build before then

**Comment by irina060981** [comment] 2019-05-24 22:21
@monzug , could you give me a password for the test user test@test.it?
That I could see this strange bug.

**Comment by monzug** [comment] 2019-05-25 15:01
psw: Test@123

iPhone xr, I can't go to show context for minus (or any other word that I scroll from the list). also show context tooltip is not generated.
on Samsung 5 mini, it works fine

**Comment by irina060981** [comment] 2019-05-27 10:23
May be it is specific for IPhone - I couldn't reproduce it on my devices :
 I login as a test@test.it
 go to the wordlist
 scroll down
 click to the icon - show context for any latin word
 it shows me context tab everytime

Don't know how to solve it

**Comment by monzug** [comment] 2019-05-27 13:44
could be iPhone specific. Known issue? @balmas?

**Comment by balmas** [comment] 2019-05-27 13:53
yes. Will debug this with you next week...

**Comment by balmas** [comment] 2019-05-27 13:53
let's leave it open but take it out of the beta

**Comment by balmas** [comment] 2019-06-07 19:10
I saw this on @monzug 's XR but not sure really what the best way to debug is because it isn't a javascript error. It did occur in both Chrome and Safari.

I was thinking maybe we need to produce some test pages with the HTML of a long wordlist and have her try loading it outside the context of the panel to isolate whether it's a problem with the wordlist html/css or the restricted space of the panel.

**Comment by balmas** [comment] 2019-06-07 19:10
what do you think @irina060981 ?

**Comment by irina060981** [comment] 2019-06-13 11:31
I have tested it on my light page
http://alpheios-test-embed.irina-sklyarova.ru
and scrolls if trying to click the link at the show context after scroll it
if click on the show context in the first words (no scroll) - it opens well.

On Samsung there is no such bug.

It is interesting scroll behaviour - it seems to me that it is some Iphone mobile browser behaviour when there are two scrolls - one inside another.

**Comment by irina060981** [comment] 2019-06-13 12:47
I think I have found the problem here - it is very IOS specific :)
We have an alph-tooltip around icons on wordlist tab. 
And tap in IOS works the following way (according to this - https://css-tricks.com/annoying-mobile-double-tap-link-issue/):

on tap first it activates hover state and then it activates click state
as for alph-tooltip - it shows tooltip on hover and as it needs to show it - it scrolls and renders a tooltip
(may be it calculates it position relatively to something - I am not sure here)

So I have removed alph-tooltip from the show context - and it stops scrolling and shows context without any problem at all. 
So I suggest to remove tooltips for mobile view - @balmas , what do you think?
Also I suggest to make buttons a little bigger.

**Comment by balmas** [comment] 2019-06-13 17:02
yes please remove the tooltips for the mobile view. 

what buttons do you want to make bigger? the show context? that's fine.

**Comment by irina060981** [comment] 2019-06-14 10:34
I mean to change it this way - so it would be a little easier to tap it:
![image](https://user-images.githubusercontent.com/12377640/59503459-c7a96a80-8ee3-11e9-8ffa-4dc5add964ee.png)

**Comment by irina060981** [comment] 2019-06-14 12:02
Merged and closed

**Comment by balmas** [comment] 2019-06-18 16:21
ready for testing at texts-test embed-lib 1.0.0.23
webextension qa-3.0.0.40

**Comment by monzug** [comment] 2019-06-20 13:50
tested in text env on mobile and desktop. IT WORKS!!!!! thanks Irina,
however the new icons are way too big also for the Samsung 5 mini. see screenshot with wrapping text 

![IMG_3628](https://user-images.githubusercontent.com/41396793/59854014-0b66fe80-9340-11e9-819a-1730ea524c0d.PNG)

as per the tooltip been removed, the delete icon is obvious, but the Show context not so much. if the tooltip is the culpit for the scrolling oddity, then I am ok with tooltips out.

**Comment by balmas** [comment] 2019-06-20 15:20
need to think about other design options here.  Coming up blank for the moment.  Maybe when the screen is below a certain size we show a single menu-like icon on each item and offer delete, show contexts and mark as important from there?

**Comment by balmas** [comment] 2019-07-23 18:47
ok, looked at this with @monzug today and the icons on the wordlist are looking fine now. Closing this.

**Comment by monzug** [comment] 2019-07-23 18:48
looks it's all fixed here

**Closed by balmas** 2019-07-23 18:47 UTC
Labels: bug
