### ISSUE TITLE
Firefox: double-click in text environment extremely slow

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#360] opened 2019-03-21 16:04 UTC
I was just checking few latin words and noticed that in Firefox the text environment is extremely slow.  I kept getting the following message: a web page is slowing down my browser. what I would like to do?
Note that my word list has only 10 words in it.
to repro:
go to  http://texts-test.alpheios.net/text/urn:cts:latinLit:phi0620.phi001.perseus-lat3/passage/1.1 in Firefox
double-click on fastus. the system takes quite sometimes  before generating the yellow message reported above. 
it's all started today 3/21/2019

**Comment by balmas** [comment] 2019-03-21 16:13
Not sure if this is related to wordlist or not yet. Need to investigate.

**Comment by monzug** [comment] 2019-03-21 16:34
let me know how I can help.

**Comment by balmas** [comment] 2019-03-21 20:24
Ok, what I'm seeing is that after a few lookups on Firefox the CPU starts churning like mad. It happens in the webextension as well as the test texts environment with the embedded library so I think it's something with the core components. I did a build with wordlists disabled and it still occurs, so I'm a little worried it's somewhere in the Vuex refactoring, although @monzug if you have been testing the in the texts environment with Firefox all along and it just started with the last build, then that makes that less likely since the Vuex code has been in for awhile. Although it could just be that latest changes somehow pushed it over the edge.   I went back a few builds and am still getting the churning in Firefox so something is definitely up.  Giving to @kirlat to investigate further.

**Comment by monzug** [comment] 2019-03-22 06:19
I confirm that I have started experiencing this since yesterday.

**Comment by kirlat** [comment] 2019-03-22 14:11
Does it happen with double-clicks handled by the instance of an embed-lib that is loaded on that page? Does it require multiple clicks on "fastus" to show itself? Or does it require clicking on some other words before?

I've tested it on the latest versions of Firefox (66, 77b3) on Windows 10, and I cannot see this effect so far. I'm wondering if it is OS dependent or not. On what OS version was you testing it? Are there any other factors that might be critical here?

**Comment by kirlat** [comment] 2019-03-22 14:16
I'm also wondering if any new build was installed on March 21st. If so, what was the previous one? If that's a matter of a build update, we can compare two versions to see what changes might be the cause.

**Comment by monzug** [comment] 2019-03-22 14:30
I clean up my environment and reboot, now it's going faster. 
to answer your question: it did happen on first double click on fastus of the day on http://texts-test.alpheios.net/text/urn:cts:latinLit:phi0620.phi001.perseus-lat3/passage/1.1

**Comment by balmas** [comment] 2019-03-22 14:36
It was a build i made from the embedded library master. But I went back several commits and was still getting significant CPU churning under Firefox in both embedded lib and web extension, after a few lookups.

**Comment by monzug** [comment] 2019-03-23 15:09
after cleaning my environment and starting from scratch, it worked fine and didn't get any of these messages: a web page is slowing down my browser.  then I started playing with lookup, word list and login and I got again the above message every time I double-clicked on any word. it's a combination of
1) lookup
2) login
3) word list
need more testing to see if I can narrow down the problem.

**Comment by monzug** [comment] 2019-03-25 10:05
I thought I could find the exact steps to repro but I haven't yet. what I can say is that:
- I do click on Show context of any word in the word list
- word list is usually between 8 to 11 words
and then I get the yellow message in firefox. After getting the message, then with almost every subsequent double-click I get the message.
see below
![IMG_3285](https://user-images.githubusercontent.com/41396793/54910868-95c7cf80-4ec3-11e9-89f0-b549f5a90dc9.JPG)

**Comment by kirlat** [comment] 2019-03-26 10:46
@monzug, thanks for detailed info on the issue! I think I can see it too, now, so I will investigate.

**Comment by monzug** [comment] 2019-03-26 10:50
@kirlat, glad I could help and that you are able to repro it now.

**Comment by kirlat** [comment] 2019-03-26 17:07
What I discovered was that for some requests that obtain a homonym from a Tufts adapter (a call to `ClientAdapters.morphology.tufts()`) it could take a significant amount of time to complete. In my tests such requests usually took around four seconds, but on some rare occasions it was much more than that. Eight to ten was not unusual, and sometimes it was even as much as sixteen full seconds!

The slow part seems to be the `fetch()` request itself. Because we're calling it in a synchronous way (with `await`), this network request effectively blocks the app's main sequence. This makes Firefox report script as unresponsive.

In my tests I was not able to find any dependency between the word used and the time needed to fulfill the request. It seemed to me that those delays happens at random. Looks like they're a matter of server being busy and/or probably unfavorable network conditions. And maybe even a matter of something else beyond our control too. 

What's interesting is that I was not able to reproduce this condition in Chrome so far. Maybe that's because `fetch` is implemented differently there.

To handle situations like this gracefully we probably should not `await` for any network calls at all (but that might require changes in the chain of our business logic). We might also set a timeout on network requests. It's not supported officially, I believe, yet there are some ways that we might explore: https://github.com/whatwg/fetch/issues/20.

**Comment by balmas** [comment] 2019-03-26 17:11
Hmm. What's interesting is that when I was testing this, I checked the response times on the server log and they were very short. Plus I have a monitor running every minute on the Morph service and I was not getting any notifications of delays that coorelated with this.

I don't think it's a network issue, but maybe Firefox's implementation of fetch is delaying for some reason (or I guess it's possible that the server isn't signaling that it is done serving data although I don't think that is it.)

**Comment by balmas** [comment] 2019-03-26 17:43
@monzug can you do me a favor and do a little testing with the released version of Alpheios and Firefox, both via the webextension and the embedded library at e.g. http://texts.alpheios.net/text/urn:cts:latinLit:phi0959.phi006.alpheios-text-lat1/ to see if you are getting the performance issues there too? Thanks!

**Comment by monzug** [comment] 2019-03-26 18:11
I will. I keep trying things to find a repro scenarios with not much luck...

**Comment by monzug** [comment] 2019-03-26 18:20
I double clicked on about 40 words on embedded library at
http://texts.alpheios.net/text/urn:cts:latinLit:phi0959.phi006.alpheios-text-lat1/passage/1.1-1.183/classical-latin-ovid-metamorphoses-alpheios-enhanced-metamorphoses
didn't get any of the yellow message on Firefox. will do more tomorrow

**Comment by monzug** [comment] 2019-03-26 18:25
got the error message on the 9th words on same text but in the test
environment on Firefox.

**Comment by balmas** [comment] 2019-03-26 18:28
ok, thanks. so that theory is not right :-) will keep hunting

**Comment by balmas** [comment] 2019-03-26 19:26
I am seeing lots of blocking in the response times for the requests in the Firefox debugger

https://stackoverflow.com/questions/43783829/what-does-blocked-really-mean-in-the-firefox-developer-tools-network-monitorin

**Comment by balmas** [comment] 2019-03-26 20:06
All that said, I really don't think this is a fetch issue or an issue with the service response times.

My hunch is that there may be number of issues, some possible introduced by Vuex, and what pushed this over the edge was the wordlists. What is interesting is that it seems much worse in the Alpheios texts environment than it does in the web extension. I don't understand why that is yet. But I turned off the wordlists entirely in the build used by that environment and it is much harder for me to reproduce the slow script error now.  @monzug do you see the same?

I DID reproduce it when I first loaded the page, and when I chose to stop the script rather than let it continue, I got this in the console:

```
 Error: Script terminated by timeout at:
reactiveGetter@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:39973:13
hasItem/<@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:67860:33
hasItem@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:67860:12
addItems@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:67839:12
addInflectionItems@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:67993:31
createInflectionSet@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:71146:13
getInflectionsData@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:82609:12
getStandardFormInstance@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:85689:26
getStandardForm@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:85301:19
getStandardForm@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:85182:44
inflView@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:25264:20
latinInflView@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:25271:14
render@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:30786:19
renderMixin/Vue.prototype._render@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:42478:17
updateComponent@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:42982:20
get@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:43388:15
Watcher@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:43377:9
mountComponent@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:42989:5
../node_modules/vue/dist/vue.js/</</Vue.prototype.$mount@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:47953:12
../node_modules/vue/dist/vue.js/</</Vue.prototype.$mount@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:50838:12
init@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:42058:9
createComponent@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:44883:11
createElm@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:44830:11
updateChildren@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:45121:13
patchVnode@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:45224:31
updateChildren@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:45098:11
patchVnode@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:45224:31
updateChildren@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:45098:11
patchVnode@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:45224:31
patch@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:45385:11
lifecycleMixin/Vue.prototype._update@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:42864:18
updateComponent@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:42982:9
get@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:43388:15
run@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:43463:19
flushSchedulerQueue@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:43221:7
nextTick/<@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:40922:11
flushCallbacks@http://texts-test.alpheios.net/assets/nemo.secondary/js/alpheios-embedded.js:40848:16
```

That is similar to what I saw last week too, and I think that is the first initialization of the inflection browser, which we have had problems with in the past.  

But I think that isn't the main issue,  which I believe is something introduced by the wordlists.  Reassigning this to myself to continue investigation.

**Comment by balmas** [comment] 2019-03-26 23:33
Now I'm wondering if there was something just really wrong with the previous build. I rebuilt the embedded library again, with wordlists re-enabled, and updated the texts-test environment and can no longer reproduce the problem.  @monzug what about you?

**Comment by kirlat** [comment] 2019-03-27 08:08
Just for reference: I was testing it in webextension that was built out of `components#master` and I was able to reproduce the issue, although it was not very frequent: I was seeing the warning one out of ten to twenty times, approximately.

**Comment by monzug** [comment] 2019-03-27 09:38
did some testing on the new text environment and it's all good, no more loading issue or warnings. However we are missing one option: world usage examples.
an other note on the build issue: chrome always worked fine, it was only reproducible in Firefox. why?

**Comment by balmas** [comment] 2019-03-27 11:38
@monzug the usage examples are there if you turn them on in the options. I think the previous build may have had some incomplete code from another branch for the usage examples, so it's quite possible the issue will return once that branch is merged. As for why it doesn't occur in Chrome, I think it's probably a difference in the way the browsers handle memory and cpu usage. I think we need to take a little time to review some aspects of the code right not to try to find trouble spots.

**Comment by monzug** [comment] 2019-03-27 13:45
agree. Thanks for the update

**Comment by monzug** [comment] 2019-03-27 13:51
@balmas, I turned on the world usage example in Options and sure enough I got the yellow warning on the second double-click.

**Comment by balmas** [comment] 2019-03-27 13:52
ok thank you! this is helpful to know. @irina060981 merged some changes for the usage examples to master today and will do some performance review on them tomorrow before we put that up for you to test again.

**Comment by monzug** [comment] 2019-03-27 13:55
ok. I am ahead on my testing, then.

**Comment by balmas** [comment] 2019-03-27 13:56
no, you were right on time :-)

**Comment by irina060981** [comment] 2019-03-28 10:49
After almost a hundred tries I was able to reproduce the Firefox message - browser is extremly slow.
And I could see the following listing:
![изображение](https://user-images.githubusercontent.com/12377640/55150599-30603100-5198-11e9-90f8-bb2602ddf4b9.png)

There were two delays (everytime with browser message):
1) 2019/03/28 @ 20:26:21 *******LexicalQuery.iterations morphology start
    2019/03/28 @ 20:26:33 *******LexicalQuery.iterations LexicalQuery.evt.MORPH_DATA_READY 1
    
    **12 seconds** for getting data from morphology tufts adapter
    but according to the Network Tab - there is no delay with the request (it has the same timing as a request without  delay) - 1457mc and the request was started at  10:26:21 and ended at 10:26:23
    
![изображение](https://user-images.githubusercontent.com/12377640/55151295-a618cc80-5199-11e9-8a7c-f41776d3ec60.png)

    and then there was a delay with a great CPU usage inside this rows:
    ```
    this.homonym = adapterTuftsRes.result
    LexicalQuery.evt.MORPH_DATA_READY.pub()
    console.info(UIController.currentDate, '*******LexicalQuery.iterations LexicalQuery.evt.MORPH_DATA_READY 1 pub end')
     ````
2) the second delay was here
    2019/03/28 @ 20:26:36 *******LexicalQuery.iterations lexicon short start
    2019/03/28 @ 20:26:49 *******LexicalQuery.iterations lexicon short end
   
    **13 seconds** for getting data from lexicons
   
![изображение](https://user-images.githubusercontent.com/12377640/55151781-b7160d80-519a-11e9-8b3d-028799258ef5.png)
      But as previous there were no abnormal delay with fetching data from lexicons
      
      I think delay here is similiar - inside publish event.
      I will try to add additional logging and reproduce it again

**Comment by irina060981** [comment] 2019-03-28 11:20
After additional logging I have commented ResourceQuery.getData (retrieving data from grammar).
And delays became 3 seconds (1.5-2 seconds for fetching data and 1 second for data handling)

**Comment by irina060981** [comment] 2019-03-28 11:47
After additional detailing I could see that great delays with great CPU usage us located inside `window.fetch` request.
For example,
![изображение](https://user-images.githubusercontent.com/12377640/55155328-c8fbae80-51a2-11e9-8bfd-6b6c5cac83f1.png)

2019/03/28 @ 21:42:55 *******BaseAdapter.fetchWindow window.fetch start
2019/03/28 @ 21:43:08 *******BaseAdapter.fetchWindow window.fetch end

**13 seconds**
and if we look at network tab - we could see that the request was only 1459ms
and all other time window.fetch was hang on with full browser blocking

**Comment by irina060981** [comment] 2019-03-28 12:10
I tried to use axios requests instead of window.fetch - and finally it hang on too.
I think, that so the problem is  not with fetching itself (axios and window.fetch use different ways to get requests).
And as I have created

**Comment by irina060981** [comment] 2019-03-28 12:45
@balmas , @kirlat  I have made a lot of tests - and browser hang on only inside window.fetch in Firefox (with browser message).
I didn't find any similiar issues with window.fetch or axios in Google.

All my tests were not using operating woth wordlist in remote, with grammar, with word usage examples.

**Comment by balmas** [comment] 2019-03-28 13:11
@irina060981 thanks for this information, it is very helpful!

**Comment by irina060981** [comment] 2019-04-11 04:57
I have created 2 additional issues (according to our discussion on the meeting) and I think I won't be able to find some other points as I couldn't reproduce overload much than 14-15% GPU for now for Firefox.

I think that as for the first step - I have removed multi-requests for grammar, some other bugs it is enough. It is better to finish with other steps (reactive properties, mutations, v-if and v-show) and look what would change :)

**Comment by balmas** [comment] 2019-04-22 18:29
@monzug let us know if you are still seeing problems and we can reopen. Thanks!

**Closed by balmas** 2019-04-22 18:29 UTC
Labels: firefox, performance

**Comment by monzug** [comment] 2019-05-15 12:36
haven't seen any problem on Firefox.
