### ISSUE TITLE
improve panel resizing

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#332] opened 2019-02-08 13:23 UTC
Right now the panel only adjusts its size for some tabs (Inflections and Diagrams) and does so somewhat imperfectly.  With the addition of usage examples and word lists, we will have some displays that need additional resizing logic.  We need to rethink this design a bit and come up with a more general solution and apply it consistently across all the panel tabs.  We might want to wait until #274 is implemented because it may influence our requirements here.

**Comment by kirlat** [comment] 2019-04-22 11:40
I cannot see any unexpected behavior in my tests with the latest version of Components. Maybe it was already fixed with the changes made to components? Probably we should retest it? What do you think?

**Comment by balmas** [comment] 2019-04-22 16:32
The initial size of the word usage examples needs improvement still. It should be expanded so that the text does not wrap (if there is enough room). 

Inflections is looking pretty good though.

**Comment by kirlat** [comment] 2019-04-25 16:32
I have found a way how, using advanced CSS grid sizing values, scale panel without JS. I think it is potentially a much better solution as:
1. It's more reliable as the browser inherently knows widths of blocks within layout and can decide on panel size much more effectively. The current calculations in JS that we are using are dependent on layout props such as paddings, layout schema, etc. and need to be updated every time we change corresponding rules of the layout.
2. It is simpler as CSS only solution allows greatly reduce an amount of code needed for resizing.
3. It is faster as no special resizing calculations will occupy the JS thread (although probably not so important in our case).

It worked well in my tests. Hope it will work well across all our supported platforms.

**Comment by kirlat** [comment] 2019-04-25 16:39
After several test on different resolutions I decided not to wrap lines of text fragments in usage examples. I think it looks really nice like that and there are very rare occasions when scrolling occurs (except for mobile). On mobile however, there is an effect of browser scaling that differs from platform to platform. The whole approach to mobile UI need to be tested on different devices and tweaked. Such tests can take quite some time and I'm not sure if we have time for that now. However, even if horizontal scrolling occurs, I think it's still much easier to read example fragments when they are in one line and with scrolling (looks like one sentence with the word selected) than if they were wrapped and be without scrolling (that will cause parts of fragments to be dislocated to additional lines and this is confusing). Please let me know what do you think.

**Comment by kirlat** [comment] 2019-04-25 16:46
I used a CSS grid to align target words among text fragments. This allow to center words across all fragments, will scale for any fragment length, and allow to avoid text overlapping as may occur on some occasions with flebox-based layout. 

The problem is, however, that we cannot use a Vue sub component to render each word usage example data as we're doing now. This is because the example data, to be placed into a grid, should be rendered as several divs by a sub-component (one for each cell such as reference link cell, prefix cell, target word cell, etc.). This means that the component must have multiple root elements (i.e. each cell is a root element), and Vue does not support it currently. We can use functional component with manual render function to overcome it, but it's a lot of trouble as it is stateless. Or we can use a crazy hack that inserts root element and then removes it after it is rendered.

However, we can stop using a subcomponent and use a `v-for` loop inside a parent component. `v-for` works fine with multiple elements, but the problem is that for mobile, by default, ref links are hidden. There is a toggle element that turns a ref link on and off for each usage example instance. This individual visibility state, however, needs to be stored somewhere, and in the design that uses `v-for` the only place is the `WordUsageExample` object. We can add a visibility prop there. It will solve our problem, but will introduce a UI-related prop into a business data object.

After some discussion with @balmas we decided to use one button that will turn links on or off on mobile for all examples at once (for now). That will allow us not to store individual state for each example fragment.

**Comment by balmas** [comment] 2019-05-02 19:53
this can be tested in 3.0.0.30 and later (and embed-lib 1.0.0.6 and later, I think)

**Closed** 2019-05-02 19:53 UTC
Labels: bug, waiting_verification

**Comment by monzug** [comment] 2019-05-24 13:38
tested in Chrome, Safari and Firefox. it looks good, sometimes I have to adjust for Inflections or Examples but mostly ok. 
Not sure if mobile is part of the scope of this issue. see comment below:
on mobile in the user word list the lemma is displayed on next line. see screenshot
![IMG_3489](https://user-images.githubusercontent.com/41396793/58330951-075dc480-7e06-11e9-8a23-9dc37b3cb701.PNG)
and with filters
![IMG_3490](https://user-images.githubusercontent.com/41396793/58331620-843d6e00-7e07-11e9-9419-9334baf1c01d.PNG)
