### ISSUE TITLE
Safari: User Panel Text

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#815] opened 2019-09-20 19:05 UTC
Let's change the text on the User Panel for Safari:

When not logged in:

*Login Instructions*

Please launch the Alpheios Reading Tools application. You can create and login to your account from there. 

Return to the browser after login.

You will stay logged in, even after the browser is closed, until you logout or your session expires.

See the [User Account Tutorial](https://alpheios.net/pages/tutorials/#safari-user-account)  for further help with logging in.

and when logged in, after the user account details:

*Logout Instructions*

Please launch the Alpheios Reading Tools application. You can logout from your account from there.

Return to the browser after logout.  

You may need to refresh or close your browser for the logout to take affect.

See the [User Account Tutorial](https://alpheios.net/pages/tutorials/#safari-user-account)  for further help with logging in.

**Comment by kirlat** [comment] 2019-09-25 09:48
I've included the changes into the `safari-authentication` branch. @balmas, can you please check it when you will have time and verify that the look and feel are matching to what's expected?

Since here we have a more complex example of a text that needs to be translated, with formatting and a link URL which shall be stored separately, there was a question of what would be the best way to store strings for translation. After giving it some thought and checking best practices I decided to proceed with putting HTML tags (trying to keep them at a minimum though) into a translation string. This is, on my opinion, is a lesser evil than splitting text into multiple chunks. A chunked text would be a translator's nightmare. Also, some languages may require a different order of formatted text or even a different formatting.

On the other hand, as no better solution exists at the moment AFAIK, translators are probably already get more accustomed to seeing tags in translatable text and get used to ignore them.

I also decided to provide URL as a parameter to a translation string utilizing those great powers that intlMessageFormat gives us. The URL itself is hardcoded in the UserAuth component, but I"m thinking probably it is smarter to have it in a separate file as we do with Auth0 data? The problem is such file does not exist yet and we will need to create it (which is not a problem at all of course). In that case it would make sense to put some other configurable attributes into it too.

Please let me know what do you think about an architecture in general and an implementation in particular. Thanks!

**Comment by balmas** [comment] 2019-09-25 12:25
this looks good to me. The only change I might suggest would be to put the user profile information above the logout instructions.

Regarding the hardcoded tutorial URL, TBH I'm okay with it staying hardcoded in the component for now.  I am remembering that I did the same for the Tutorial link in the info.vue component as well. I think it would be good to have a way to externalize these in the future, but it can wait.

**Comment by balmas** [comment] 2019-09-25 19:35
QA 3.0.1.72/Components 1.2.47 (Safari build in Dropbox)

**Comment by monzug** [comment] 2019-09-27 12:54
please change take affect with take effect
also, in logging out we have:
"See the User Account Tutorial for further help with logging out" which I think it's ok. however in the above text we have
See the User Account Tutorial for further help with logging in.

**Comment by kirlat** [comment] 2019-09-27 13:42
I slightly changed the last word in a text for the logout (from "logged in" to "logged out") because I thought there was a typo. @balmas, please let me know which variant is correct.

**Comment by monzug** [comment] 2019-09-27 13:55
I agree with u. still we need to change take effect

**Comment by balmas** [comment] 2019-09-27 13:58
yes, sorry about that, it was my typo in both cases. I struggle with affect and effect... :-)

**Comment by kirlat** [comment] 2019-09-27 14:01
I will update the text

**Comment by kirlat** [comment] 2019-09-27 14:59
A fix has been merged into master

**Closed** 2019-09-30 11:48 UTC
Labels: auth, design, waiting_build

**Comment by balmas** [comment] 2019-10-01 12:29
qa 3.0.1.74/components 1.2.50

**Comment by monzug** [comment] 2019-10-01 13:25
fixed.
