### ISSUE TITLE
state issues with lookup box and morph component

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#347] opened 2019-03-07 15:55 UTC
I think this was introduced by the vuex refactoring

from @monzug 
1) go to Catullus, Carmina poem 68b.31-60
http://texts-test.alpheios.net/text/urn:cts:latinLit:phi0472.phi001.perseus-lat2/passage/68b.31-68b.60
2) double click on Troia, Alpheios does not recorgnize the word (which I believe it should but this is not the point), then double click on other word, e.g. obscena
3) enter Troia in the the lookup field.
4) the output will be again the obscena word
repeat with caro, obscena will show up again in the morphology panel.
Note that define and inflection do display the correct output for the lookup word.

**Comment by kirlat** [comment] 2019-04-17 17:15
I think this has been probably fixed in the current release. I'm not able to reproduce it in the local test environment.

**Comment by monzug** [comment] 2019-04-19 14:13
tested in test environment on firefox in build 3.0.0.28

**Closed by monzug** 2019-04-19 14:13 UTC
Labels: verified
