### ISSUE TITLE
Memory management

### ISSUE THREAD

**Issue by kirlat** [alpheios-project/components#231] opened 2018-10-01 11:12 UTC
@irina060981 reported that there are memory leaks in embedded version of Alpheios. There are memory leaks in webextension as well.

This issue is created as a way to track problems with memory leaks and memory bloat and the progress in solving them. It also can be a way to share best practices in hunting such issues down.

Many of the issues arise from errors or inefficiencies of the code. In such cases objects can be retained for longer than they should be or even forever. However, some of the issues may be a result of a current app architecture. It is important to discuss such issues and produce best practices that can be used to avoid memory-related problems in the future.

**Comment by kirlat** [comment] 2018-10-01 11:46
I've submitted a first attempt to fix most sever issues. Here are some changes made and lessons learned.

One of the most important changes was related to the use of `interact.js`. Interact object attaches itself to the HTML node. In case of inflection table footnotes, it was attached to the footnote popup.

Before we were attaching an Interact object to each footnote popup at the `mounted` callback of `infl-footnote` Vue component. However, there were two problems with that. The first one was that many Interact object were created for each footnote popup even if most of them would never be opened by the user. That was causing a noticeable slowdown at table creation. It also increased memory footprint. The second, most important, issue what that those Interact object were never deleted thus creating a memory leak.

I decided that it would be better to create and attach an Interact object to the footnote popup the moment popup is open and destroy it the moment popup is closed. This has several advantages:
 - There is only one such Interact object at a time, or several, at most, if there are several footnote popups opened simultaneously. This greatly reduces an overall table memory footprint.
 - As we destroy an Interact memory object the moment popup is closed, there is no memory leak.
The drawback is that it might take a little longer for footnote popup to open, but I did not notice any real life delay in my tests. It might be noticeable, however, on slower devices, so we need to test that thoroughly.

Please let me know what do you think about this change and about the strategy we used  for that. Would it work? What do you think?

**Comment by balmas** [comment] 2018-10-01 12:34
@monzug please take a look at this in https://github.com/alpheios-project/webextension/tree/memleaks/dist

**Comment by kirlat** [comment] 2018-10-01 14:57
@monzug, thanks for the info, I will test it to see if I can reproduce that

**Comment by kirlat** [comment] 2018-10-01 16:13
@monzug, sorry for the issue with morphology highlighting. Was so concentrated on tracking memory usage that missed such an obvious thing. Please check an updated build: https://github.com/alpheios-project/components/archive/memleaks.zip.

I was not able to reproduce an issue with footnote popups, however. What's the best way to reproduce it? I was clicking on footnotes and tried to move a popup opened. Have from 10 to 15 of them, but still was able to move them. Tested in Chrome 69 and FF 63b10 on Windows 10. Please see a screenshot below:
https://github.com/alpheios-project/components/archive/memleaks.zip
![image](https://user-images.githubusercontent.com/18631055/46301015-2f1dc500-c5b6-11e8-9156-09ec2fa47638.png)

Is it a correct way to reproduce it? If it is, then maybe I'm missing some specific details, like what table is it, how many popups do I need to open?

**Comment by monzug** [comment] 2018-10-01 16:17
I'll get back to you on the steps to repro. will install next build soon.
Thanks

**Comment by monzug** [comment] 2018-10-01 18:58
install latest fix from  https://github.com/alpheios-project/webextension/tree/memleaks/dist (I got 'page not found' from the archive link). the cell are highlighted now. Thanks!

about the fixed pop-up, I didn't write the steps to repro because I was able to reproduce it all the time. 
Unfortunately, I took a break and forgot how to repro.... soooo, I got the fixed pop-up only once in the latest build and I don't know how. I took a screenshot but I do not think it can be of any help.

![fixed-pop-up](https://user-images.githubusercontent.com/41396793/46309421-4e066200-c58a-11e8-849e-37ca50320d78.JPG)

will try again tomorrow morning with a clear mind.

**Comment by balmas** [comment] 2018-10-01 18:59
@irina060981 in your testing can you also try to see if you can reproduce this? Thanks!

**Comment by balmas** [comment] 2018-10-01 22:08
I have created a new build, https://github.com/alpheios-project/webextension/tree/memleaks2/dist
There are no new fixes for this issue in it, but it contains fixes from the master branch from other issues fixed today, so please use this for testing. Thanks!

**Comment by irina060981** [comment] 2018-10-02 06:07
@kirlat and @balmas, hello!
Yes, I was able to reproduce a bug with footnote popup - it becomes unmovable if you open footnote popup - it is movable, than close it and open again. After these steps it becomes fixed to the place.

**Comment by monzug** [comment] 2018-10-02 09:09
it did happen again few times this morning on latest build.

**Comment by irina060981** [comment] 2018-10-02 11:40
I have made a series of memory testing with Chrome Dev Tools (webextension).
And I couldn't find any memory extreme raising - everything is in 100-300 MB load - and I didn't see in memory snapshots any extremely large objects or some Deattached objects in great amounts now in this branch..

**Comment by kirlat** [comment] 2018-10-02 11:53
Thanks for notes on how to reproduce an issue with the popup interaction. I can see it now too. Will work on a fix.

**Comment by balmas** [comment] 2018-10-02 14:06
merged to master and can be tested in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-17/dist

**Comment by monzug** [comment] 2018-10-02 15:52
happy to say that so far so good!!!!

**Comment by monzug** [comment] 2018-10-02 16:19
looks good to me. Thanks

**Comment by irina060981** [comment] 2018-10-03 09:46
Hello, @balmas, @kirlat and @monzug!
Only now I was able to rebuild safari extension with all new libs (because there were some strange problems with XCode - it seems to me that Apple tools are not so perfect as it is declared).

And I could see that it uses more RAM than in Chrome (I didn'y compare with Firefox if to be honest)

It used in 300-600 Mb RAM, and some clear processes in memory happen with greater delay than in Chrome.
Here are some screenshots
<img width="1380" alt="screen shot 2018-10-03 at 19 33 16" src="https://user-images.githubusercontent.com/12377640/46403106-f2340880-c744-11e8-8244-b91e600d45e3.png">

<img width="1413" alt="screen shot 2018-10-03 at 19 34 00" src="https://user-images.githubusercontent.com/12377640/46403114-f52ef900-c744-11e8-84e7-ad90f6364e4d.png">

![Uploading Screen Shot 2018-10-03 at 19.34.39.png…]()

**Comment by balmas** [comment] 2018-10-03 11:41
Thanks @irina060981 ! I will make a copy of this issue in the safari-app-front repo so that we don't forget to look closely at it there.

**Closed by balmas** 2018-10-03 11:41 UTC
Labels: bug, verified
